### ISSUE TITLE
[Release 1v1 [RANK] Barren Badlands Balanced ZH v1] Bottom right bunker by oil derrick is hitting terrain

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#1]
Bottom right bunker by oil derrick is hitting terrain and damaging itself when shooting with rocket men.

![shot_20210213_215411_1](https://user-images.githubusercontent.com/4720891/107862243-d3cd9400-6e4b-11eb-92e8-e335edcb7003.jpg)

**Comment by ReLaX82** [comment]
Please leave a comment on the change posted inside https://www.gamereplays.org/community/index.php?showtopic=1048527&st=120&gopid=10395749&#entry10395749.

- Bugfixing for bunker, impassable and passable terrain, symmetry in terms of civilian building at oil. Top-left had none, now it has.

**Comment by xezon** [comment]
Fixed with [RANK] Barren Badlands Balanced ZH v1
