### ISSUE TITLE
[Release 1v1 [RANK] Melting Snow ZH v3] Cars are usable

### ISSUE THREAD

**Issue by RisingZH** [xezon/GeneralsRankedMaps#10]
Cars top middle and bottom left

**Comment by ReLaX82** [comment]
2 Cars removed. Map see https://www.gamereplays.org/community/index.php?showtopic=1048527.

**Comment by xezon** [comment]
[RANK] Melting Snow ZH v4 has been added. Check if all cars are removed.

**Comment by xezon** [comment]
Fixed in [RANK] Melting Snow ZH v4
