### ISSUE TITLE
[Candidate 2v2 [RANK] Rubies and Pearls ZH v1] Snow map has cricket sounds

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#100]
**Issue Description**
Snow map has cricket sounds.

**Expected behavior**
There are no cricket sounds on snowy terrain.

**Comment by xezon** [comment]
[RANK] Rubies and Pearls ZH v1
There are still cricket sounds in the map center.

**Comment by Jundiyy** [comment]
[[RANK] Rubies and Pearls ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6215850/RANK.Rubies.and.Pearls.ZH.v1.zip)
I have replaced it with dog sounds.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/e4b54760cfc49f087731158a808dc7fa3050f30a
