### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] .map file size is very large compared to regular 1v1 maps

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#103]
**Issue Description**
Freezing Rain map file is very large. 1.3MB. Previous version was just 0.1MB. Last change increased size by 1.2MB
https://github.com/xezon/GeneralsRankedMaps/commit/1804b4f91724b4784c23d7d21c713effff5c9a25

**Expected behavior**
Typical map size is 0.1 or 0.2MB

**Comment by Millard9** [comment]
can you please check if this is fixed in the newest version i sent please?

**Comment by xezon** [comment]
.map size is 1.3 MB

**Comment by Millard9** [comment]
I imagen it to do with this error when tying to save. I am not sure quite how to fix this i will try thing and see what happens.
![image](https://user-images.githubusercontent.com/81384841/112751557-a76a7300-8fc6-11eb-8522-47c4aa6fecfb.png)

**Comment by Millard9** [comment]
ahhh Issue has been fixed. will upload again to GameReplays
![image](https://user-images.githubusercontent.com/81384841/112751644-f0222c00-8fc6-11eb-938b-4b64b6724e4f.png)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/769fb90ef8041ad78527cc2775ac6b318652f6c0
