### ISSUE TITLE
[Candidate 3v3 Coral Islands WBC [WBC Winner]] Title text shows up way too long and late and has no credits

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#104]
**Issue Description**
Title text shows map name. No credits. Shows up way too late and long.

**Expected behavior**
There is no title text if it has no credits.

**Screenshots**
![shot_20210327_115514_2](https://user-images.githubusercontent.com/4720891/112718563-2642ab80-8ef4-11eb-83c2-ecf0bea2d634.jpg)

**Comment by Jundiyy** [comment]
[Coral_Islands_WBC_-.zip](https://github.com/xezon/GeneralsRankedMaps/files/6264977/Coral_Islands_WBC_-.zip)
Mapper has edited as requested.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/2cc7e530573642ab758adb67493651edefa300fa
