### ISSUE TITLE
[Candidate 3v3 Subjugation Mk 14 [WBC Winner]] All supplies have very little money (main supply $15.000)

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#108]
**Issue Description**
All supplies have very little money (main supply $15.000). Is this ok?

**Expected behavior**
Supplies have a fair amount of cash.

**Screenshots**
![shot_20210327_122301_6](https://user-images.githubusercontent.com/4720891/112719230-2e9ce580-8ef8-11eb-909f-1310ec7974d6.jpg)

![shot_20210327_122621_8](https://user-images.githubusercontent.com/4720891/112719234-3492c680-8ef8-11eb-8dfc-c58dfb0f28c8.jpg)

**Comment by Jundiyy** [comment]
It is okay since the 2 Oils will keep your economy going, but would prefer some more in the main. Middle ones being less doesn't really matter, you have more supplies to fight over.

**Comment by Jundiyy** [comment]
25k + would be nice. Otherwise the Dock would run dry after 5-7 mins and you would be down to 1 supply (2 oils).

**Comment by kABUSE1** [comment]
I think this is part of design and shouldn't be changed completely.

It makes the map unique, as you have to fight for external ressources extra hard. Anyway, I increased the base supplies to 20k and the two supplies in middle to 25k.

I think it's a good compromise, but of course subject to change if you all disagree.
[Subjugation Mk 14 [WBC Winner].zip](https://github.com/xezon/GeneralsRankedMaps/files/6370477/Subjugation.Mk.14.WBC.Winner.zip)

**Comment by Jundiyy** [comment]
15k is fine, increasing from 15k is not a must, map will work fine, yes you're right it would force you to go out. Another reason to keep 15k is to look at it as only a 3v3 map. Only suggested 25k so bigger battles go on for longer, once the supplies run dry it auto reduces the battles or unit count.

**Comment by xezon** [comment]
Changed with https://github.com/xezon/GeneralsRankedMaps/commit/354b483148cdc34e48eafa1f437cf5f6f92213c6
