### ISSUE TITLE
[Candidate 3v3 Territorial Dispute] Map preview image is too detailed

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#110]
**Issue Description**
Map preview image is too detailed.

**Expected behavior**
Map preview image has same style like any Official Map.

**Screenshots**
![shot_20210327_123529_13](https://user-images.githubusercontent.com/4720891/112719543-bc2d0500-8ef9-11eb-8b89-d1d099a4a6e0.jpg)

**Comment by Jundiyy** [comment]
Hmmm, I do get your point on having the same style but I think it looks much better? Of course we can't force everyone to make the detailed ones (it's half simple to do) but it's nice to have them.
Of course no harm in not having them.

**Comment by xezon** [comment]
If every preview was like then ok, but all Ranked Maps and Official Maps have auto generated less detailed map previews so it should be consistent.

**Comment by Newgate-M17** [comment]
I'll also work on this one

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/cc77ccce49d1b39333aa7ab90892e35e46b3ac9b
