### ISSUE TITLE
[Candidate 3v3 Territorial Dispute] Title text shows up too late

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#111]
**Issue Description**
Title text shows up too late.

**Expected behavior**
Title text shows right after map load.

**Screenshots**
![shot_20210327_123618_14](https://user-images.githubusercontent.com/4720891/112719582-dff04b00-8ef9-11eb-8f0a-0e79195f24ba.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by Jundiyy** [comment]
I could be wrong but I think this is the map that he put a lock on, I asked him to unlock it a few weeks ago but he said if you need it unlocked then let me know. I can ask or you can.

**Comment by xezon** [comment]
Not fixed in latest version. Title text shows a few seconds after map begin, which is a few seconds later than necessary. Text ends at 13 seconds, which is quite long into the map time.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/4fc34771d255eee8924641e429f18e127f01d148
