### ISSUE TITLE
[Candidate 3v3 Territorial Dispute] Oil derrick flag is covered by structure

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#113]
**Issue Description**
Oil derrick flag is covered by structure.

**Expected behavior**
Oil derrick flag is always visible with default camera rotation.

**Screenshots**
![shot_20210327_123740_15](https://user-images.githubusercontent.com/4720891/112719644-31003f00-8efa-11eb-9d3e-42c51e0c184e.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by Newgate-M17** [comment]
All issues fixed

[Territorial Dispute.zip](https://github.com/xezon/GeneralsRankedMaps/files/6388686/Territorial.Dispute.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/cc77ccce49d1b39333aa7ab90892e35e46b3ac9b
