### ISSUE TITLE
[Candidate 1v1 [RANK] Bursting Asunder ZH v1] Does Bursting Asunder.wak has correct name?

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#114]
**Issue Description**
Does Bursting Asunder.wak has correct name?

**Expected behavior**
Bursting Asunder.wak works correctly.

**Screenshots**
![burstingasunder](https://user-images.githubusercontent.com/4720891/112720170-0663b580-8efd-11eb-9a37-d0023d819d27.png)

**Comment by Jundiyy** [comment]
Oh sorry, I forgot to rename that. I can do that for you soon.

**Comment by xezon** [comment]
I can do it.

**Comment by xezon** [comment]
Please check if correct:
https://github.com/xezon/GeneralsRankedMaps/tree/main/candidate/maps_2v2_zh/%5BRANK%5D%20Bursting%20Asunder%20ZH%20v1

**Comment by Jundiyy** [comment]
Yes looks correct, thank you.
