### ISSUE TITLE
[Release 1v1 [RANK] Tournament in the Canyon vB] Player is unable to see terrain at all map borders (top)

### ISSUE THREAD

**Issue by RisingZH** [xezon/GeneralsRankedMaps#12]
Field of view - top

**Comment by SpeCoV1k** [comment]
Hmmm >:( here i again not understand what problem :O https://www.youtube.com/watch?v=OLWlYHp3q0U

**Comment by xezon** [comment]
@RisingZH please explain problem.

**Comment by RisingZH** [comment]
@SpeCoV1k 

https://imgur.com/a/ZdeMdKS

The issue is that if you are USA on the top spot you are unable to select your chinooks when they are collecting without rotating the camera angle. This is not very satisfactory for competitive play.

**Comment by SpeCoV1k** [comment]
Its ok? https://www.gamereplays.org/community/uploads/post-103811-1617455545.png

**Comment by xezon** [comment]
@RisingZH

**Comment by RisingZH** [comment]
Looks good.

**Comment by xezon** [comment]
Can you send updated map?

**Comment by SpeCoV1k** [comment]
> Can you send updated map?

https://drive.google.com/file/d/1lFf2GR_B44DbGt91xAbMM8FlAkUYeQxx/view?usp=sharing

**Comment by xezon** [comment]
Can you upload map here instead of third party website?

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/a4d625a5111a29e4f35a0473d74b409c304ef5bc
