### ISSUE TITLE
[Candidate 1v1 [RANK] Melting Snow ZH v4] Infantry can move through fence

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#121]
**Issue Description**
Infantry can move through fence.

**Expected behavior**
Infantry cannot move through fence.

**Screenshots**
![shot_20210328_141054_12](https://user-images.githubusercontent.com/4720891/112751697-9c681080-8fcf-11eb-9e47-86be89a718da.jpg)

**Comment by ReLaX82** [comment]
After testing 5 minutes forth and back a fence at the edge is in most cases passable to an extent.
My decision is to delete it here, it may be different with other fences.
Fixes also impassable terrain right top of the map together with water tank placement.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/ed405e6ca1e66ca1e43b42f7c11329f3747b4c14
