### ISSUE TITLE
[Candidate 1v1 [RANK] Barren Badlands Balanced ZH v2] Left oil has fences that block infantry and right oil does not

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#122]
**Issue Description**
Left oil has fences that block infantry and right oil does not.

**Expected behavior**
Oils have the same fencing or no fencing.

**Screenshots**
![shot_20210328_142518_15](https://user-images.githubusercontent.com/4720891/112752210-26b17400-8fd2-11eb-81d4-9b6adb45fe5e.jpg)

![shot_20210328_142529_16](https://user-images.githubusercontent.com/4720891/112752212-29ac6480-8fd2-11eb-96e6-5ca9d7a92330.jpg)

**Comment by ReLaX82** [comment]
Removed both fences left side as right side has none.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/1204950dff475706bee291225dc384c73db555ad
