### ISSUE TITLE
[Candidate 1v1 [RANK] Barren Badlands Balanced ZH v2] Left oil derrick is floating

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#123]
**Issue Description**
Left oil derrick is floating.

**Expected behavior**
Oil derrick sits on ground.

**Screenshots**
![shot_20210328_142434_14](https://user-images.githubusercontent.com/4720891/112752243-519bc800-8fd2-11eb-9462-c34aac2e81f5.jpg)

**Comment by ReLaX82** [comment]
Fixed.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/1204950dff475706bee291225dc384c73db555ad
