### ISSUE TITLE
[Candidate 1v1 [RANK] Barren Badlands Balanced ZH v2] Area at left oil visually looks worse than it did in version 1

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#124]
**Issue Description**
Version 1 left oil area looked beautiful. Version 2 left oil area looks bad.

**Expected behavior**
Left oil area looks nice.

**Screenshots**
Version 2
![shot_20210328_143456_18](https://user-images.githubusercontent.com/4720891/112752332-e1417680-8fd2-11eb-8d91-cc1875589bd8.jpg)

Version 1
![shot_20210328_142837_17](https://user-images.githubusercontent.com/4720891/112752336-e56d9400-8fd2-11eb-8b93-cf3cd0a1e749.jpg)

**Comment by ReLaX82** [comment]
Depends a little what you think looks good/bad, I uploaded another try on GR.

**Comment by xezon** [comment]
Looks better I think. Is it possible to make non intractable cars and structures not clickable? Right now when sending units there, player must be careful to not click cars. But clicking cars has no useful purpose. So I think is better to not have them clickable.

![shot_20210329_112650_2](https://user-images.githubusercontent.com/4720891/112817129-65066c00-9082-11eb-80a0-5df390ac3942.jpg)

![shot_20210329_112656_3](https://user-images.githubusercontent.com/4720891/112817149-6a63b680-9082-11eb-9a90-e2587e29e986.jpg)

**Comment by ReLaX82** [comment]
Cleaned a little more and put objects to dead which worked.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/4a509aadd0be403e9a4342ee13cdb877e5f270f4

![shot_20210401_095440_2](https://user-images.githubusercontent.com/4720891/113262191-a3916600-92d0-11eb-85c2-b9176a21b5a4.jpg)
