### ISSUE TITLE
 [Candidate 1v1 Tournament Himalaya V4] Road segments require polishing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#125]
**Issue Description**
Road segments do not align properly at various locations.

**Expected behavior**
Road segments have smooth slopes and are connected properly.

**Screenshots**
![shot_20210330_101500_2](https://user-images.githubusercontent.com/4720891/112958229-8b8bdc00-9142-11eb-93ca-45190287422a.jpg)

![shot_20210330_101518_3](https://user-images.githubusercontent.com/4720891/112958231-8cbd0900-9142-11eb-96bb-057c3df1a6b8.jpg)

![shot_20210330_101539_4](https://user-images.githubusercontent.com/4720891/112958233-8d559f80-9142-11eb-94b0-ef1bb3600efd.jpg)

![shot_20210330_101545_5](https://user-images.githubusercontent.com/4720891/112958235-8d559f80-9142-11eb-8159-ebe0688b6c22.jpg)

![shot_20210330_101642_6](https://user-images.githubusercontent.com/4720891/112958240-8dee3600-9142-11eb-8288-7aa1ab18290d.jpg)

![shot_20210330_101713_7](https://user-images.githubusercontent.com/4720891/112958243-8e86cc80-9142-11eb-8c34-a9925c957535.jpg)

![shot_20210330_101736_8](https://user-images.githubusercontent.com/4720891/112958245-8f1f6300-9142-11eb-9490-60a294211af5.jpg)

![shot_20210330_101802_9](https://user-images.githubusercontent.com/4720891/112958249-8fb7f980-9142-11eb-8e27-57a386ebe93f.jpg)

**Comment by A5SA5SIN** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/81484691/113490251-74ab0800-94fb-11eb-8c46-9e8114e03b57.png)
do you think? this ok this the best  i can do

**Comment by xezon** [comment]
Difficult to judge from image. It would be better to attach map to post instead.

**Comment by A5SA5SIN** [comment]
![Screenshot (115)](https://user-images.githubusercontent.com/81484691/113491244-e71ee680-9501-11eb-8cd3-1a9d131beb27.png)

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V4work3.zip](https://github.com/xezon/GeneralsRankedMaps/files/6253373/Tournament.Himalaya.V4work3.zip)
it's not finalized yet but i will realease the real version 4 once everything is ok

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V4.zip](https://github.com/xezon/GeneralsRankedMaps/files/6266446/Tournament.Himalaya.V4.zip)
here it is version 4
i hope the ambient sound not too noisy

**Comment by xezon** [comment]
Ok. I will check this week.

**Comment by xezon** [comment]
Main intersections and tunnels still don't look good. There is room for improvement.

![shot_20210411_163814_8](https://user-images.githubusercontent.com/4720891/114308602-d4e60f00-9ae4-11eb-8d89-0810dde847b8.jpg)
![shot_20210411_163852_10](https://user-images.githubusercontent.com/4720891/114308604-d57ea580-9ae4-11eb-8d08-6c079f4f8b1c.jpg)
![shot_20210411_163955_11](https://user-images.githubusercontent.com/4720891/114308608-d6173c00-9ae4-11eb-92a2-758e5d510a12.jpg)

**Comment by xezon** [comment]
I also added 2 new design issues:
https://github.com/xezon/GeneralsRankedMaps/issues/147
https://github.com/xezon/GeneralsRankedMaps/issues/148

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/576e07c829929417cae0bccb509a9473977fc9a4
