### ISSUE TITLE
[Candidate 1v1 The Valley ZH v1] Change map name?

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#127]
**Issue Description**
Map name is ok, but a bit boring. Maybe rename to Victory Valley or some other?

**Comment by ReLaX82** [comment]
Okay, no problem.

**Comment by ReLaX82** [comment]
Blossoming Valley I found the most attracting idea. See upload on GR.

**Comment by xezon** [comment]
Is now Blossoming Valley ZH v1
