### ISSUE TITLE
[Candidate 1v1 The Valley ZH v1] Supply piles in center are not mirrored

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#128]
**Issue Description**
Supply piles in center are not mirrored.

**Expected behavior**
Supply piles in center are mirrored.

**Screenshots**
![shot_20210330_231112_3](https://user-images.githubusercontent.com/4720891/113058645-b57ae800-91ae-11eb-9326-addd9cb5f681.jpg)

**Comment by ReLaX82** [comment]
Done.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/747cf94bec785adbb3c3c488250fcc705a17a85d
