### ISSUE TITLE
[Candidate 1v1 Egyptian Oasis ZH v1] Structures in map corners look bad

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#130]
**Issue Description**
Structures in map corners look bad.
The dam does not look good, because the terrain beneath it looks strange and the black faded mountains do not match.
The pyramids and sphinx do not look good, because they extent too far into the black map border.

**Expected behavior**
Map corners are beautifully crafted.

**Screenshots**
![shot_20210401_101159_3](https://user-images.githubusercontent.com/4720891/113265015-f15b9d80-92d3-11eb-97d3-50eb6189e2a9.jpg)

![shot_20210401_101212_4](https://user-images.githubusercontent.com/4720891/113265025-f4568e00-92d3-11eb-802d-ee57a94df308.jpg)

![shot_20210401_101225_5](https://user-images.githubusercontent.com/4720891/113265042-f7ea1500-92d3-11eb-873b-6662e06fadf2.jpg)

**Comment by ReLaX82** [comment]
Mounted the pyramids inside now with lower height.
Just have a look.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/c57ce6e07c423a8bc335d5977d36cb96bead11a4

The pyramid corner looks really nice. The water corner looks ok, but nothing special. Maybe you could bury the Sphinx into rocks like you did with the pyramids? Either way, the issue is fixed.

**Comment by xezon** [comment]
![shot_20210402_110609_3](https://user-images.githubusercontent.com/4720891/113402063-ba08f180-93a4-11eb-8629-e2d3eeffce4e.jpg)

![shot_20210402_110641_4](https://user-images.githubusercontent.com/4720891/113402070-be350f00-93a4-11eb-89dc-4aada310ac74.jpg)

**Comment by ReLaX82** [comment]
Made a smal polish as I wanted to know in first instance what you think about it overall. 
I tried to include the Sphinx, but that has not looked good to me at all.

**Comment by xezon** [comment]
I am not a fan of these triangular lakes but ok. It is acceptable. Issue is resolved.
