### ISSUE TITLE
[Candidate 1v1 Egyptian Oasis ZH v1] Too many chicken sounds at right side middle farm

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#131]
**Issue Description**
Too many chicken sounds at right side middle farm.

**Expected behavior**
Chickens occasionally make sounds, but not all the time non-stop.

**Screenshots**
![shot_20210401_101338_6](https://user-images.githubusercontent.com/4720891/113265429-6af38b80-92d4-11eb-9b5f-977d66db3dff.jpg)

**Comment by ReLaX82** [comment]
Deleted 2 of 3 in this area and moved one to the right border.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/c57ce6e07c423a8bc335d5977d36cb96bead11a4
