### ISSUE TITLE
[Candidate 1v1 Egyptian Oasis ZH v1] Odd grass patch is placed in top base

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#132]
**Issue Description**
Odd grass patch is placed in top base.

**Expected behavior**
No such grass patch there.

**Screenshots**
![shot_20210401_101526_7](https://user-images.githubusercontent.com/4720891/113265558-94acb280-92d4-11eb-83e9-2f3dd39cb400.jpg)

**Comment by ReLaX82** [comment]
Fixed, update see GR.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/c57ce6e07c423a8bc335d5977d36cb96bead11a4
