### ISSUE TITLE
[Candidate 1v1 Blossoming Valley ZH v1] Ambient sounds at right side middle section are very loud

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#133]
**Issue Description**
Ambient sounds at right side middle section are very loud.

**Expected behavior**
Ambient sounds are not overwhelming.

**Screenshots**
![shot_20210401_102910_9](https://user-images.githubusercontent.com/4720891/113266330-71363780-92d5-11eb-8af0-498dcd37e214.jpg)

**Comment by ReLaX82** [comment]
There were a lot and next version is better.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7ff6e783d5e190ac33c81641dba9f743b8307c28
