### ISSUE TITLE
[Candidate 1v1 Scorching Heat Draft 2] Wind audio is very unpleasing when scrolling around map quickly

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#136]
**Issue Description**
Wind audio is very unpleasing when scrolling around map quickly.

**Expected behavior**
Wind audio never cuts off or in drastically but has smooth sound.

**Comment by xezon** [comment]
The issue title ideally matches the map name that resides in the repository, otherwise a name search will not work correctly.

**Comment by Jundiyy** [comment]
Ah my bad, no worries, I will rename it for you, I just like to update the maps to help keep track of them on my side.
[Scorching Heat Draft 1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6278490/Scorching.Heat.Draft.1.zip)

**Comment by xezon** [comment]
Fixed in https://github.com/xezon/GeneralsRankedMaps/issues/136
