### ISSUE TITLE
[Candidate 1v1 [RANK] Sovereignty ZH v1] Wind audio is very unpleasing when scrolling around map quickly

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#137]
**Issue Description**
Wind audio is very unpleasing when scrolling around map quickly.

**Expected behavior**
Wind audio never cuts off or in drastically but has smooth sound.

**Comment by Jundiyy** [comment]
Edited the wind sounds to match the ones in the staff room.
[[RANK] Sovereignty ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6272015/RANK.Sovereignty.ZH.v1.zip)

**Comment by Jundiyy** [comment]
Same as the other map.
[[RANK] Sovereignty ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6297840/RANK.Sovereignty.ZH.v1.zip)

**Comment by xezon** [comment]
I noticed on other maps with wind, the wind audio typically kicks in a few moments after arriving with camera near audio emitter, whereas on your maps wind audio kicks in immediately. I think this is the main problem. There is no smooth transition and it just plays instantly, so user hears the sound at full volume and it cuts off when scrolling from emitter to emitter.

**Comment by xezon** [comment]
Sounds acceptable with https://github.com/xezon/GeneralsRankedMaps/commit/a6f334199ee58adbc39732e00c1527e1f8e5a01d

It's not perfect, but other maps sounds like this as well.
