### ISSUE TITLE
[Candidate 1v1 [RANK] The Survivors ZH v1] Wind audio is very unpleasing when scrolling around map quickly

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#138]
Issue Description
Wind audio is very unpleasing when scrolling around map quickly.

Expected behavior
Wind audio never cuts off or in drastically but has smooth sound.

**Comment by Jundiyy** [comment]
Edited the wind sounds to match the ones in the staff room.
[[RANK] The Survivors ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6272018/RANK.The.Survivors.ZH.v1.zip)

**Comment by Jundiyy** [comment]
Not sure if you've looked at this map and Sovereignty yet, since you've passed Scorching Heat on this issue and I fixed them all the same way.

**Comment by xezon** [comment]
I checked. Issue is not fixed.

**Comment by Jundiyy** [comment]
Thanks, please drop a message so I know since I was waiting. I actually don't know what else to do since I did the exact same changes that I did in the staff room and also to Scorching Heat Draft 2.
Please tell me exactly where the problem is on this map, I scrolled around as I would but I don't hear anything different to what ZH provides.

**Comment by xezon** [comment]
I could create an audio recording.

**Comment by Jundiyy** [comment]
Could you please make a 30s/1 min unlisted video for me? I'd also understand the scrolling then.

**Comment by Jundiyy** [comment]
I have extended all wind sounds by about 20%, so they should travel further now. Also increased the sounds a bit closer to default (had lowered them since in staff room you said they sounded better).
[[RANK] The Survivors ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6297833/RANK.The.Survivors.ZH.v1.zip)

**Comment by xezon** [comment]
I noticed on other maps with wind, the wind audio typically kicks in a few moments after arriving with camera near audio emitter, whereas on your maps wind audio kicks in immediately. I think this is the main problem. There is no smooth transition and it just plays instantly, so user hears the sound at full volume and it cuts off when scrolling from emitter to emitter.

**Comment by xezon** [comment]
Not fixed.

**Comment by Jundiyy** [comment]
Please tell me which one you like better,
A is the same wind on the map but moved from the start pos
B is new wind sound.
I'd prefer A if both are a pass.

[[RANK] The Survivors ZH v1 A.zip](https://github.com/xezon/GeneralsRankedMaps/files/6330500/RANK.The.Survivors.ZH.v1.A.zip)
[[RANK] The Survivors ZH v1 B.zip](https://github.com/xezon/GeneralsRankedMaps/files/6330501/RANK.The.Survivors.ZH.v1.B.zip)

**Comment by xezon** [comment]
A is not fixed.
B is better. Sound fades in later and thus hides the issue.

I forwarded the issue to I^Love^Mixery. He provided a version with fixed audio:

[RANK_The_Survivors_ZH_v1_test.zip](https://github.com/xezon/GeneralsRankedMaps/files/6353363/RANK_The_Survivors_ZH_v1_test.zip)

He can provide information on how to fix the audio issues in your maps.

**Comment by Jundiyy** [comment]
Thanks. I'll download and take a look when I can. Just had a chat with him and he did the same thing which I had done for you previously lol, but the difference was he changed the parameters even more than what I did.

**Comment by Jundiyy** [comment]
I suppose it's more noticeable on my maps because I have wind nearly everywhere. Thanks and thanks to I Love Mixery. I suppose a natural fix could be to change the ini code for the win sounds so it naturally starts with good parameters.

**Comment by Jundiyy** [comment]
Okay so I took the map Mixery had fixed and edited vA accordingly, since it had the original sounds, (I copied every value he entered), the map he had fixed was vB (new sounds).
[[RANK] The Survivors ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6355513/RANK.The.Survivors.ZH.v1.zip)

**Comment by xezon** [comment]
Very nice. I will check later. Could you apply the same fixes for all your other new maps?

**Comment by Jundiyy** [comment]
Done.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/9a1f14ad72835e6f61263099c97140421b99dd16
