### ISSUE TITLE
[Candidate 1v1 Oil Rampage V3] Map preview image is too detailed

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#139]
**Issue Description**
Map preview image is too detailed.

**Expected behavior**
Map preview is soft like and normal like all other map preview images from official maps.

**Screenshots**
![shot_20210402_102215_2](https://user-images.githubusercontent.com/4720891/113397498-6fd04200-939d-11eb-9cb9-b7ccb4b397d0.jpg)

**Comment by TKLyo** [comment]
[Oil Rampage v4.zip](https://github.com/xezon/GeneralsRankedMaps/files/6264982/Oil.Rampage.v4.zip)

I've made changes to everything and also tried to position all the oil derricks and supplies accordingly to make it symmetrical

**Comment by TKLyo** [comment]
[Uploading Oil Rampage v5.zip…]()
Remove a single hut in both player's side to make it less bunkery :)

**Comment by xezon** [comment]
You can do that for next years submission. This years submissions ended March 31. Now is polishing phase to solve issues.

**Comment by TKLyo** [comment]
ah alright, thanks. also I've sent u the latest version of Oil Rampage

**Comment by xezon** [comment]
I will review it shortly.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/218c7f4a46da1979962784e20ddbd865eed68b38
