### ISSUE TITLE
[Candidate 1v1 Drallim Desert v2] Units can drive over steep terrain

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#141]
**Issue Description**
Units can drive over steep terrain.

**Expected behavior**
Units cannot drive over steep terrain.

**Screenshots**
![shot_20210405_191209_11](https://user-images.githubusercontent.com/4720891/113602614-1d17b400-9643-11eb-9091-6a6183ded719.jpg)
![shot_20210405_191215_12](https://user-images.githubusercontent.com/4720891/113602616-1e48e100-9643-11eb-9d47-371fec706ef0.jpg)

**Comment by xezon** [comment]
![shot_20210405_191959_16](https://user-images.githubusercontent.com/4720891/113603218-f60db200-9643-11eb-87bc-0e16eef679f3.jpg)

**Comment by Jundiyy** [comment]
Terrain doesn't look too steep, World Builder automatically makes steep terrain impassable, it's just a mound, imagine it wasn't a mound and the land was raised behind it, it's the same height but without the back area being higher. Although my advice to Millard was to make it impassable but for balance reasons, not the reason above.

**Comment by Millard9** [comment]
This issue has been fixed

**Comment by xezon** [comment]
No.

**Comment by Millard9** [comment]
Maybe I forgot to send the updated version. I'll send this later today.

**Comment by xezon** [comment]
I checked updated map. I see no difference. Units can still climb really steep hills.
The easiest fix for the bumps in the center would be to make them flatter.
And for the hills near oil do not allow units to climb on hill too far.

![shot_20210429_130642_1](https://user-images.githubusercontent.com/4720891/116541650-0421bc00-a8ec-11eb-8f48-7911717dafe5.jpg)

![shot_20210429_130657_2](https://user-images.githubusercontent.com/4720891/116541657-07b54300-a8ec-11eb-9bf2-a9355e9eac91.jpg)

**Comment by Jundiyy** [comment]
I hope this one will suffice, the mounds are around 20% lower now. Also the corners have more impassable tiles.
[Drallim Desert v2 vA.zip](https://github.com/xezon/GeneralsRankedMaps/files/6408783/Drallim.Desert.v2.vA.zip)

**Comment by xezon** [comment]
Bumps in center are very good now. Terrain near oil can also not longer be climbed. Fixed.
