### ISSUE TITLE
[Candidate 1v1 Drallim Desert v2] Rocks around UN crate look repetitive

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#142]
**Issue Description**
Rocks around UN crate look repetitive.

**Expected behavior**
Rock formation looks unique.

**Screenshots**
![shot_20210405_191608_15](https://user-images.githubusercontent.com/4720891/113602964-a202cd80-9643-11eb-8894-d5c9fbd6ebc6.jpg)

**Comment by Millard9** [comment]
do you want me to turn the rocks?

**Comment by xezon** [comment]
Different rotations on rocks would potentially fix the issue.

**Comment by Millard9** [comment]
Cool I sent you new version in discord with the fix



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 05/04/2021 21:46 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Comment ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Drallim Desert v2] Rocks around UN crate look repetitive (#142)


Different rotations on rocks would potentially fix the issue.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/1130c5bf8ac2ad7b28c8ff25a070f55392a0e673
