### ISSUE TITLE
[Candidate 1v1 [RANK] Forgotten Air Battle ZH v6] Structures have pink tint

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#143]
**Issue Description**
Structures have pink tint.

**Expected behavior**
Structures have natural color matching terrain and ambient color.

**Screenshots**
![shot_20210405_215910_17](https://user-images.githubusercontent.com/4720891/113620628-df268a00-965a-11eb-8d74-67df2925daaa.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by kABUSE1** [comment]
Fixed by mp3.
[RANK_forgotten_air_battle_v6.zip](https://github.com/xezon/GeneralsRankedMaps/files/6370819/RANK_forgotten_air_battle_v6.zip)

**Comment by xezon** [comment]
RANK_forgotten_air_battle_v6.zip does not seem to be based on the latest version from GitHub, so we have to reject the edit from Mp3.

**Comment by kABUSE1** [comment]
I informed mp3.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7082fbd581227df432f92a147075d79878f385aa
