### ISSUE TITLE
[Candidate 1v1 Scorching Heat Draft 2] Map terrain has many obvious tiles

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#144]
**Issue Description**
Map terrain has many obvious tiles.

**Expected behavior**
Terrain texture is beautifully crafted to hide tiles.

**Screenshots**
![shot_20210406_224623_2](https://user-images.githubusercontent.com/4720891/113777045-e1581980-972a-11eb-8c5a-39e086b5ebcf.jpg)

**Comment by xezon** [comment]
Yes such terrain patches will hide the tiles and is generally desired.

**Comment by Jundiyy** [comment]
Got you.

**Comment by Jundiyy** [comment]
Is this now closed? I changed them tiles.

**Comment by xezon** [comment]
Issue is still there.

**Comment by Jundiyy** [comment]
Sorry maybe I didn't get something, I thought you said the edit I made was right?

**Comment by xezon** [comment]
No I don't think so. There are many tiles visible on this map.

**Comment by Jundiyy** [comment]
Then I don't understand what visible tiles means. Please explain further. I thought you were referring to the main texture I used but it seems not. I don't see any tiles in the pic you showed.

**Comment by xezon** [comment]
When you look at first screenshot, you see tile pattern in sand texture. Ideally this is hidden by crafting textures better. It's not a major issue, but other RANKED maps do this better, so it's worth mentioning here.

**Comment by Jundiyy** [comment]
[Scorching Heat Draft 2.zip](https://github.com/xezon/GeneralsRankedMaps/files/6297724/Scorching.Heat.Draft.2.zip)
Okay I understand what you mean, the tiles become repetitive after a while since ZH only has a limited amount that can be used. So you meant there are many similar tiles in one place and the pattern repeats.
I think the problem is that the base texture that I used is quite rich in this map so it stands out more, I used this texture as it had a lot on it and thought it would fill up parts of the map better. Anyway, please take a look now.

**Comment by xezon** [comment]
It's this one sand texture that shows obvious tiling. It looks as if it should be used more sparingly and another texture needs to be the dominant one.

![shot_20210417_110155_19](https://user-images.githubusercontent.com/4720891/115107662-acd72f80-9f6c-11eb-96d9-0f2ade6a7ca5.jpg)

**Comment by Jundiyy** [comment]
Ah I didn't see that part, grrrr, and yep that's the base texture I used. It's quite rich and shows itself more obviously as you have pointed out.
I'll get to it.

**Comment by Jundiyy** [comment]
There aren't many places left now right? I did cover many places in the last upload. I'd rather not change the base texture this late into it as some other textures might not match the new base texture. I also liked the brightness of this texture compared to the ones I usually use. So I'd rather just fix up the few left.

**Comment by xezon** [comment]
Yes terrain looked better overall in last version.

**Comment by Jundiyy** [comment]
[Scorching Heat Draft 2.zip](https://github.com/xezon/GeneralsRankedMaps/files/6330499/Scorching.Heat.Draft.2.zip)
I hope this can be the final texture edit.

**Comment by Jundiyy** [comment]
[[RANK] Scorching Heat ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6355473/RANK.Scorching.Heat.ZH.v1.zip)
Removed Jarmen voice as well. Please take this as a final version.

**Comment by Jundiyy** [comment]
[[RANK] Scorching Heat ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6358457/RANK.Scorching.Heat.ZH.v1.zip)
Updated with new sound values.

**Comment by xezon** [comment]
Fixed
