### ISSUE TITLE
[Candidate 2v2 Whispering Woods v1x10] Grass and rock terrain shows very obvious tiles everywhere

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#145]
**Issue Description**
Grass and rock terrain shows very obvious tiles everywhere.

**Expected behavior**
Terrain texture is beautifully crafted.

**Screenshots**
![shot_20210411_162534_1](https://user-images.githubusercontent.com/4720891/114308175-39a06a00-9ae3-11eb-9e2d-c555b64d8554.jpg)
![shot_20210411_162552_2](https://user-images.githubusercontent.com/4720891/114308178-3a390080-9ae3-11eb-9c86-ea0a140c525d.jpg)
![shot_20210411_162604_3](https://user-images.githubusercontent.com/4720891/114308179-3ad19700-9ae3-11eb-84b4-c01bedfb508a.jpg)

**Comment by xezon** [comment]
Looks much better already. There is still this one texture though with very obvious tiling. Maybe this can be improved further.

![shot_20210417_111158_3](https://user-images.githubusercontent.com/4720891/115107956-23286180-9f6e-11eb-9e43-8d878f4fa040.jpg)

**Comment by JoKeRZH429** [comment]
[Whispering_Woods_v1x21.zip](https://github.com/xezon/GeneralsRankedMaps/files/6369581/Whispering_Woods_v1x21.zip)

Should be fine in this version

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/72455958ea3d3c0e2de543468d02e6b3151f0203
