### ISSUE TITLE
 [Candidate 1v1 Tournament Himalaya V4] Some mountain tops are very flat

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#147]
**Issue Description**
Some mountain tops are very flat.

**Expected behavior**
Mountains look natural.

**Screenshots**
![shot_20210411_163833_9](https://user-images.githubusercontent.com/4720891/114308819-681f4480-9ae5-11eb-803c-db16cb28efa5.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/576e07c829929417cae0bccb509a9473977fc9a4
