### ISSUE TITLE
[Candidate 1v1 Tournament Himalaya V4] Base number "2" is up side down

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#148]
**Issue Description**
Base number "2" is up side down.

**Expected behavior**
There are no base numbers.

**Screenshots**
![shot_20210411_163713_5](https://user-images.githubusercontent.com/4720891/114308861-8dac4e00-9ae5-11eb-9703-33989d7b3602.jpg)

**Comment by A5SA5SIN** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/81484691/115188863-23fcf700-a118-11eb-9c66-a0364df8286f.png)
![Screenshot (121)](https://user-images.githubusercontent.com/81484691/115188870-28291480-a118-11eb-9fdd-28b97e267322.png)
![Screenshot (122)](https://user-images.githubusercontent.com/81484691/115188877-29f2d800-a118-11eb-9694-554a6c3155b5.png)
![Screenshot (123)](https://user-images.githubusercontent.com/81484691/115188884-2c553200-a118-11eb-8bf3-114f12d79cec.png)
![Screenshot (124)](https://user-images.githubusercontent.com/81484691/115188903-324b1300-a118-11eb-8c87-9599e11852a6.png)
![Screenshot (125)](https://user-images.githubusercontent.com/81484691/115188920-38d98a80-a118-11eb-8353-a6774cd451c7.png)

**Comment by A5SA5SIN** [comment]
the roads are fix and i removed the numbers just like you asked

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V5inprogress.zip](https://github.com/xezon/GeneralsRankedMaps/files/6333619/Tournament.Himalaya.V5inprogress.zip)
here in progress version

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V5.zip](https://github.com/xezon/GeneralsRankedMaps/files/6353113/Tournament.Himalaya.V5.zip)
here the version 5

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V5.zip](https://github.com/xezon/GeneralsRankedMaps/files/6353130/Tournament.Himalaya.V5.zip)
ok here the version 5

**Comment by xezon** [comment]
Ok. I will check soon.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/576e07c829929417cae0bccb509a9473977fc9a4
