### ISSUE TITLE
[Candidate 1v1 Scorching Heat Draft 2] Jarmen audio plays at start of map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#149]
**Issue Description**
Jarmen audio plays at start of map.

**Expected behavior**
No Jarmen audio at start of map.

**Comment by Jundiyy** [comment]
Roger, will be removed once the final version is ready.

**Comment by Jundiyy** [comment]
Fixed in #144

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7f48790fb6865a7d621efb67cafd45d6048930bc
