### ISSUE TITLE
[Candidate 1v1 Oil Rampage V3] Intro text shows too long

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#150]
**Issue Description**
Intro text shows longer than expected.

**Expected behavior**
Intro text shows just as much as other Ranked Maps (less than 10 seconds).

**Screenshots**
![shot_20210411_165945_14](https://user-images.githubusercontent.com/4720891/114309465-7706f680-9ae7-11eb-946b-cc6e8c1c8577.jpg)

**Comment by TKLyo** [comment]
[Oil Rampage v6.zip](https://github.com/xezon/GeneralsRankedMaps/files/6331476/Oil.Rampage.v6.zip)

Fixed the briefing text to 10seconds. Here's the file to the map

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/6cd42d2335d391350957600261bc2e78b0141b7a
