### ISSUE TITLE
[Candidate 1v1 [RANK] Make Make 2 ZH v4] AI Army spawns Defeated

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#152]
**Issue Description**
AI Army spawns Defeated.

**Expected behavior**
AI Army spawns Playing.

**Screenshots**
![shot_20210417_095920_7](https://user-images.githubusercontent.com/4720891/115106298-40583280-9f64-11eb-8176-71c578450c5e.jpg)

**Comment by Jundiyy** [comment]
What is different in this version? Reason for update?

**Comment by xezon** [comment]
Check "Make Make" issue reports.

**Comment by Jundiyy** [comment]
I don't know if this will fix it as not able to get on ZH just yet but I saw a fault in the map when opened in World Builder. 
[[RANK] Make Make 2 ZH v4.zip](https://github.com/xezon/GeneralsRankedMaps/files/6358472/RANK.Make.Make.2.ZH.v4.zip)

**Comment by Jundiyy** [comment]
[[RANK] Make Make 2 ZH v4.zip](https://github.com/xezon/GeneralsRankedMaps/files/6360331/RANK.Make.Make.2.ZH.v4.zip)
I noticed he also didn't add any attack paths, so I have added them in as well.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/53254f0674a942da711104da1b417f6f331fcd68
