### ISSUE TITLE
[Candidate 4v4 Dusty Rampage v3] AI in top right corner does not build supply and anything beyond that

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#153]
**Issue Description**
AI in top right corner does not build supply and anything beyond that.

**Expected behavior**
All AI's build base and tanks.

**Screenshots**
![shot_20210417_103709_15](https://user-images.githubusercontent.com/4720891/115107108-21a86a80-9f69-11eb-9481-9579d262c668.jpg)

**Comment by Newgate-M17** [comment]
I'll work on fixing this one

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/00581a2df6dd7c3a5b393962607ef1ae5878d9ce
