### ISSUE TITLE
[Candidate 4v4 Dusty Rampage v3] Ambient audio cuts poorly when scrolling over map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#154]
**Issue Description**
Ambient audio cuts poorly when scrolling over map.

**Expected behavior**
Ambient audio fades in and out nicely when scrolling over map.

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by mp36660** [comment]
> I'll work on this one

Thank you for assisting! Make sure to name the finalized version v4.

**Comment by Newgate-M17** [comment]
👍

**Comment by xezon** [comment]
Map name version does not matter in Candidate maps. Map will be renamed when moved to Release maps.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/00581a2df6dd7c3a5b393962607ef1ae5878d9ce
