### ISSUE TITLE
[Candidate 1v1 Glacial Horses V2] Units can move into fountain structure

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#156]
**Issue Description**
Units can move into fountain structure.

**Expected behavior**
Units cannot move into large structures.

**Screenshots**
![shot_20210417_104644_16](https://user-images.githubusercontent.com/4720891/115107411-f6bf1600-9f6a-11eb-8cbb-ca613d3947fa.jpg)

**Comment by kABUSE1** [comment]
It is fixed, I made a small impassable area beneath it. But consider that if you remove the fountain by building right next to it, you will now NOT be able to build where it originally was. Only a tiny area, probably neglectable.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/353361557b8676cc8180236f5800b013ee54bcc7
