### ISSUE TITLE
[Candidate 2v2 Whispering Woods v1x10] Top center command center clips in terrain

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#157]
**Issue Description**
Top center command center clips in terrain.

**Expected behavior**
Command centers spawn above terrain.

**Screenshots**
![shot_20210417_110922_1](https://user-images.githubusercontent.com/4720891/115108002-5f5bc200-9f6e-11eb-8f54-3c08a4478ad0.jpg)

![shot_20210417_110932_2](https://user-images.githubusercontent.com/4720891/115108003-5ff45880-9f6e-11eb-8a24-a90e384b3fd4.jpg)

**Comment by JoKeRZH429** [comment]
[Whispering_Woods_v1x21.zip](https://github.com/xezon/GeneralsRankedMaps/files/6369585/Whispering_Woods_v1x21.zip)

Should be fine in this version

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/72455958ea3d3c0e2de543468d02e6b3151f0203
