### ISSUE TITLE
[Candidate 1v1 Arab Tragedy ZHv3] Map is very badly balanced.

### ISSUE THREAD

**Issue by Jundiyy** [xezon/GeneralsRankedMaps#158]
**Issue Description**
Most supplies and tech buildings are not placed equally for both players.

**Expected behavior**
Most supplies and tech buildings are placed equally for both players.

![BottomSupps](https://user-images.githubusercontent.com/79164303/115720938-6ec77a80-a375-11eb-9510-b70e2aaaf6e9.PNG)

**Comment by TKLyo** [comment]
Taking this over

**Comment by kABUSE1** [comment]
Thanks for taking over, Lyo.

The most imminent balancing issues in purple.
The rest in blue.
Also put some distances in white

<img width="773" alt="Tragedy Issues" src="https://user-images.githubusercontent.com/47530719/115961628-850d3c00-a517-11eb-9f29-0249aa1137ad.png">

**Comment by Jundiyy** [comment]
Very nice.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/4638621dc9bead2f455e04457ce248ad8f6526b4
