### ISSUE TITLE
 [Candidate 2v2 Bricks 2v2 ZH v1] AI Trigger areas are not correctly placed

### ISSUE THREAD

**Issue by kABUSE1** [xezon/GeneralsRankedMaps#160]
**Issue Description**
AI area are wrongfully placed.

**Expected behavior**
AI area are correctly placed.

**Comment by kABUSE1** [comment]
AI issues fixed here:
[Bricks 2v2 ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6370541/Bricks.2v2.ZH.v1.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/46f13a6b2d6ad92413ff1834bcbdd188ac518601
