### ISSUE TITLE
[Candidate 1v1 Tragedy Tracks] Are 3 piles on secondary supply sufficient?

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#166]
**Issue Description**
Are 3 piles on secondary supply sufficient?
There are another 3 supplies a bit further away.
Split secondary supplies favors USA faction.

**Screenshots**
![shot_20210428_130943_6](https://user-images.githubusercontent.com/4720891/116395849-f0f7e900-a824-11eb-8a90-840f6a70c70c.jpg)

**Comment by Jundiyy** [comment]
![basesupp](https://user-images.githubusercontent.com/79164303/116413249-594bc800-a82f-11eb-9938-53dca9cf8d5d.PNG)
This is the latest version, which is good but I'd prefer 5 due to the map size.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/8e311c8cf1238a2572d3a953559b01fd392f2c5f
