### ISSUE TITLE
[Candidate 1v1 [RANK] Forgotten Air Battle ZH v6] Shadow color is way too saturated for given time of day

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#169]
**Issue Description**
Shadow color is way too saturated for given time of day.

**Expected behavior**
Blue shadow color is less saturated when daylight is not blue tint either.

**Screenshots**
![shot_20210428_134021_13](https://user-images.githubusercontent.com/4720891/116398316-f276e080-a827-11eb-9f40-4a055c186222.jpg)

![shot_20210428_134050_14](https://user-images.githubusercontent.com/4720891/116398329-f4d93a80-a827-11eb-9b40-900553a10978.jpg)

**Comment by Newgate-M17** [comment]
Here's a side-by-side comparison of the changes:
![Shadow Comparison](https://user-images.githubusercontent.com/81472427/116570680-095b2700-a93d-11eb-9de1-b94db6860b20.png)


[[RANK] Forgotten Air Battle ZH v6.zip](https://github.com/xezon/GeneralsRankedMaps/files/6399513/RANK.Forgotten.Air.Battle.ZH.v6.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7bc9ab532287ca3394e297e8fd64618696041ff1
