### ISSUE TITLE
[Candidate 1v1 [RANK] Tournament in the Canyon vB1] People audio is too loud and distracting

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#173]
**Issue Description**
People audio by the tents is too loud and distracting.

**Expected behavior**
Ambient sounds do not distract player.

**Screenshots**
![shot_20210428_205105_8](https://user-images.githubusercontent.com/4720891/116457420-afd2f980-a863-11eb-8a4a-0cf482cb7b52.jpg)

![shot_20210428_205115_9](https://user-images.githubusercontent.com/4720891/116457434-b2355380-a863-11eb-8c7d-e5bedf309d7b.jpg)

**Comment by Jundiyy** [comment]
I'll take a look at this tomorrow if Spec doesn't already.

**Comment by Jundiyy** [comment]
Check #174

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/0b63cc1128222e7341d0bc2eddef96784b3b9ed2
