### ISSUE TITLE
[Candidate 1v1 [RANK] Tournament in the Canyon vB1] GLA terrorist can use 2 cars on map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#174]
**Issue Description**
GLA terrorist can use 2 cars on map.

**Expected behavior**
All cars cannot be used by GLA.

**Screenshots**
![shot_20210428_212440_10](https://user-images.githubusercontent.com/4720891/116461537-a6985b80-a868-11eb-8763-6b2c2aabb4fa.jpg)
![shot_20210428_212625_12](https://user-images.githubusercontent.com/4720891/116461540-a730f200-a868-11eb-8f0b-385ce1119539.jpg)

**Comment by Jundiyy** [comment]
Mine if Spec does not.

**Comment by Jundiyy** [comment]
Found 4 cars - fixed
AI didn't have attack paths - added
Top player start pos was a bit off - balanced
Issue #173 fixed here as well (I hope), I have reduced the sounds by half or a bit more.
[[RANK] Tournament in the Canyon vB1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6399070/RANK.Tournament.in.the.Canyon.vB1.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/0b63cc1128222e7341d0bc2eddef96784b3b9ed2
