### ISSUE TITLE
[Candidate 2v2 FallOut ZH v1] Map center has player spawn

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#175]
**Issue Description**
Map center has player spawn.

**Expected behavior**
Map center has no player spawn.

**Screenshots**
![shot_20210429_131133_3](https://user-images.githubusercontent.com/4720891/116542770-544d4e00-a8ed-11eb-8a36-38ebd4fd46c0.jpg)

**Comment by Jundiyy** [comment]
Lol, how did that even happen? Maybe Newgate was checking the map or something. Anyways working on this now.

**Comment by Jundiyy** [comment]
[FallOut ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6398973/FallOut.ZH.v1.zip)
Removed the extra player and also added in attack paths for the AI.

**Comment by Newgate-M17** [comment]
Yeah,  I was checking the AI all worked lol
Sorry about that

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7eee412ecaf64c2f55a5f685912257c9b4faee61
