### ISSUE TITLE
[Candidate Fun Mortal_Temptation [WBC2020]] Stylized map preview image does not fit overall style of map preview images

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#177]
**Issue Description**
Stylized map preview image does not fit overall style of map preview images.

**Expected behavior**
Map preview image looks more like regular map preview.

**Screenshots**
![shot_20210429_134837_4](https://user-images.githubusercontent.com/4720891/116546475-f1aa8100-a8f1-11eb-85d3-9fff4a8ce406.jpg)

**Comment by Jundiyy** [comment]
I have added the original preview image, but it doesn't look nice at all compared to the one above, maybe something in between could be done, because looking at the original just looks bad after looking at the new one.
[Uploading Mortal_Temptation [WBC2020].zip…]()

**Comment by Jundiyy** [comment]
[Uploading Mortal_Temptation [WBC2020].zip…]()

**Comment by Jundiyy** [comment]
[Mortal_Temptation [WBC2020].zip](https://github.com/xezon/GeneralsRankedMaps/files/6399158/Mortal_Temptation.WBC2020.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/8746fa6dc268d5b463e0cd562973312c4d63c78b
