### ISSUE TITLE
[Candidate 1v1 Oil Oasis ZH v1] Right and left center are too narrow

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#20]
**Describe the bug**
Right and left center are too narrow. Please refer to Jundiyy for more information.

**Expected behavior**
Right and left center have more room.

**Comment by ReLaX82** [comment]
What is meant by too narrow in this case? What does it mean "Right and left center have more room" ?

**Comment by ReLaX82** [comment]
Has been explained here: https://www.gamereplays.org/community/index.php?showtopic=1048527&st=120&gopid=10395763&#

**Comment by xezon** [comment]
Jundiyy:
"Regarding 24me, Mp3 already messaged me and said he had already tested what I mentioned and said it was fine, so I will take my back what I said. (I only said "it seems", didn't test yet.) I was worried that units would have difficulty passing from the right side of the middle to the left side of the middle during mid and eco-late games. Simply because there is no other bigger path (unless you go through the base)."

**Comment by xezon** [comment]
Fixed or no issue.
