### ISSUE TITLE
[Candidate 1v1 Arab Tragedy ZHv2] Pad structure at the top is not balanced

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#21]
**Describe the bug**
Pad structure at the top is not balanced. Please refer to Jundiyy for more information.

**Expected behavior**
Pad structure at the top is balanced.

**Comment by Jundiyy** [comment]
Answered over here #22

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/fec5c24c70a72c32dc61aedda0db98749da52b59

**Comment by Jundiyy** [comment]
Top pad
![toppad](https://user-images.githubusercontent.com/79164303/115718147-c6181b80-a372-11eb-9b07-b842ef877ef0.PNG)
Bottom pad
![bottompad](https://user-images.githubusercontent.com/79164303/115718164-c9130c00-a372-11eb-8113-bd321337b838.PNG)
The top pad isn't at an equal distance to both players and neither is the bottom pad.
Even if you look at this from a different way, 1 pad for each player, it still isn't equal.

**Comment by xezon** [comment]
Ok. Can you fix it?

**Comment by kABUSE1** [comment]
This issues should be closed as the balancing problems are all covered here:
https://github.com/xezon/GeneralsRankedMaps/issues/158
