### ISSUE TITLE
[Candidate 1v1 Arab Tragedy ZHv2] Base entrances are a bit too narrow

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#22]
**Describe the bug**
Base entrances are a bit too narrow. Please refer to Jundiyy for more information.

**Expected behavior**
Base entrances have proper width.

**Comment by Jundiyy** [comment]
I've given Spec a detailed answer through discord along with some other improvements.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/fec5c24c70a72c32dc61aedda0db98749da52b59
