### ISSUE TITLE
[Candidate 2v2 FallOut ZH v1] Supply and oil positions require tweaking

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#23]
**Describe the bug**
Supply and oil positions require tweaking. Please refer to Jundiyy for more information.

**Expected behavior**
Supply and oil positions are properly placed.

**Comment by Jundiyy** [comment]
I will do this, hopefully tonight after work.

**Comment by Jundiyy** [comment]
[FallOut ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6396113/FallOut.ZH.v1.zip)
Done the tweaking and also removed the texture in #96.
Found 4 cars in the middle which I have set to non-useable (I hope).

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/706590269a242fc8c05cfdb34a4ae54cc8fcd9bb
