### ISSUE TITLE
[Candidate 1v1 Glacial Horses V1] Requires unspecified tweaks

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#27]
**Describe the bug**
Map requires unspecified tweaks for competitive experience and release status. Please refer to Relax for more information.

**Comment by RisingZH** [comment]
This map has a weird pink glow which I don't like. It prevents oils flashing a player's colour when capturing.

**Comment by xezon** [comment]
This should be tracked as separate issue with a screenshot. Likely ambient light is poorly setup.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/d0658d193a96c0877f08444b867c728e4766d5e7
