### ISSUE TITLE
[Candidate 1v1 Planet Coyon V3] Terrain textures are too simplistic

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#29]
**Describe the bug**
Terrain textures are too simplistic. Please refer to Relax for more information.

**Expected behavior**
Terrain textures are beautiful.

**Comment by xezon** [comment]
Not fixed in Planet Coyon V2.

![shot_20210405_184937_1](https://user-images.githubusercontent.com/4720891/113600626-9366e700-9640-11eb-9c09-95130f43cdfa.jpg)
![shot_20210405_184948_2](https://user-images.githubusercontent.com/4720891/113600629-9530aa80-9640-11eb-8e87-c5860a531155.jpg)
![shot_20210405_185004_3](https://user-images.githubusercontent.com/4720891/113600632-9661d780-9640-11eb-95f0-4324dee384db.jpg)
![shot_20210405_185019_4](https://user-images.githubusercontent.com/4720891/113600638-96fa6e00-9640-11eb-9cd0-987bded88934.jpg)
![shot_20210405_185129_5](https://user-images.githubusercontent.com/4720891/113600640-982b9b00-9640-11eb-9c9f-c123c5ec8bf4.jpg)

**Comment by xezon** [comment]
It's a bit better. Still many tiles are visible on this map, which happens because the grass texture has very distinct features. For it to look beautiful, you need to paint terrain better.
![shot_20210413_000535_6](https://user-images.githubusercontent.com/4720891/114468986-9f2c4d80-9bec-11eb-97ab-5ec45b7ed992.jpg)

**Comment by xezon** [comment]
**Planet Coyon V4**: I don't see much of a difference. The main grass texture is still too prominent and its tiles are visible everywhere.

**Comment by Jundiyy** [comment]
I told FireArm that I will help him.

**Comment by kABUSE1** [comment]
Assigning to Jundiyy as he already talked to the dude I suppose

**Comment by Jundiyy** [comment]
If you'd like to take over, I don't mind. I just saw the dude trying multiple times, here and discord so I thought I'd guide him a bit.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/0b6c21dc4be66036a8cb88a5726792fbbe789ff3
