### ISSUE TITLE
[Candidate 1v1 Farmlands of the Fallen ZH v3] Terrain around top left supplies cannot be built on properly

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#30]
**Describe the bug**
Terrain around top left supplies cannot be built on properly.

**Expected behavior**
Terrain around supplies is flat and allows supply placements.

**Comment by ReLaX82** [comment]
Made a topic in which Bamovich can respond.

I am pretty sure he would accept my changes.

Made equal room for corner piles, enough to be able to build supply and WF.

Hight of farms inside middle also made equal to 20 as it was a bit different in few places.
Same goes for spawn position, height 50.

https://www.gamereplays.org/community/index.php?showtopic=1051084

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/694e3526fa111d1bb0997d43d1dfc84052b0de7e
