### ISSUE TITLE
[Release 1v1 [RANK] Canyon of the Dead v1] Cars in towns are usable

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#31]
**Describe the bug**
Cars in towns are usable.

**Expected behavior**
Cars in towns are not usable.

**Comment by ReLaX82** [comment]
I can do that Furthermore I can also make the symmetry a bit better and delete some terrain issues.
Also map naming should be changed then to ZH v2 as a v1 already exist.

**Comment by ReLaX82** [comment]
See also: https://github.com/xezon/GeneralsRankedMaps/issues/4

**Comment by ReLaX82** [comment]
Specovic said in one topic that I could change the map.

Things I have done: 
- Middle supply small piles placed equally.
- 2nd supply nearby balanced for both spots; it was very wrong like I thought!
- Arti and oil placed symmetrical and 45/90° orientation.
- City nearby completely balanced now.
- Removed all cars

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/3763eb1c1c1fa7771faa4e4f90c9833947a8b621
