### ISSUE TITLE
[Candidate 1v1 24me ZH v1] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#33]
**Issue Description**
Map name is unacceptable. 24me is abstract in map context and does not describe a place.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by ReLaX82** [comment]
What about **Two Oils Derricks**  or **Nearby Oils**?

**Comment by xezon** [comment]
I have not seen the map but I assume there are 2 oils close to the main base.
Maybe **Precious Haven**?

**Comment by ReLaX82** [comment]
Sicherer Hafen in German.

I can live with that one, thx!

**Comment by xezon** [comment]
**Safe Haven** translates to Sicherer Hafen.
**Precious Haven** translates to Kostbarer Hafen.

**Comment by xezon** [comment]
Fixed (Oil Oasis ZH v1)
