### ISSUE TITLE
[Candidate 1v1 Arab Tragedy ZHv3] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#34]
**Issue Description**
Map name is unacceptable. Arab Tragedy can be interpreted as an insult to Arabs.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by kABUSE1** [comment]
Some suggestions from the discord:
Tragedy Tracks
Arab Prosperity
A New Tragedy

My vote goes for "Tragedy Tracks", got a really nice ring to it and makes sense.

**Comment by xezon** [comment]
Map will be renamed to `[RANK] A New Tradegy ZH v1`
