### ISSUE TITLE
[Candidate 1v1 Battle Star ZH v1] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#35]
**Issue Description**
Map name is unacceptable. Battle Star sounds like something from outer space and does not describe an earthly place.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by ReLaX82** [comment]
I don't really get what is wrong with such a name.

**Comment by xezon** [comment]
Battle Star map name does not fit into the realms of official map names. Original maps are named like "Green Pastures", "Tournament Desert". I could understand something like "Battle Plan" or "Battle Station". But **Battle Star** is not from Earth.

**Comment by ReLaX82** [comment]
Battle Star is pointing to the center of the map as there are 6 tech buildings forming a circle or a star.

**Comment by xezon** [comment]
I will reject this name for now and look for new name suggestions.

**Comment by ReLaX82** [comment]
Here are my suggestions:
1) Battle Plan
2) Mid Oils
3) Barren Battleground

ReLaX

**Comment by xezon** [comment]
Battle Plan is good name I think.

**Comment by ReLaX82** [comment]
Okay, accepted. Map uploaded on GR.

**Comment by xezon** [comment]
Map has been renamed to Battle Plan.
