### ISSUE TITLE
[Candidate 1v1 Modern Warfare ZH v1] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#36]
**Issue Description**
Map name is unacceptable. Modern Warfare is abstract in map context and does not describe a place.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by ReLaX82** [comment]
I don't really get what is wrong with such a name.

**Comment by xezon** [comment]
Modern Warfare does not refer to a map location or map situation. The terminology feels disconnected from a map.

**Comment by ReLaX82** [comment]
I have no idea how to name it and I am bit scared which map name changes are coming next.
Don't think any name should refer to a map location or map situation.

Can only think of something with Green then, like Green battleground or similar.

Any ideas?

**Comment by ReLaX82** [comment]
So, my suggestions are the following:

1) Green Battleground
2) Autumn Farmlands
3) Fertile Countryside

**Comment by xezon** [comment]
Autumn Farmlands looks very good I think.

**Comment by ReLaX82** [comment]
Better, will rename!

**Comment by ReLaX82** [comment]
Abandoned Farms it is now!

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/8e8751f7df7370d814ae670cd1041492da7dcad0
