### ISSUE TITLE
[Candidate 1v1 [RANK] Final Crossroad ZH v2] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#37]
**Issue Description**
Map name is unacceptable. Wavefall is abstract in map context and makes it difficult to associate a map design with. Also it should not contain **1vs1** tag.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by KaSSaDo** [comment]
Referring to the dominant crossroads you see on the map thumbnail as well as on the minimap:
Charming Crossroads ZH v1
Calm Crossroads ZH v1
Jazzy Junctions ZH v1
Casual Crossroads ZH v1
Crisp Crossroads ZH v1
Catchy Crossroads ZH v1
Callow Crossroads ZH v1
Callous Crossroads ZH v1


Junction

**Comment by xezon** [comment]
Maybe **Final Crossroad** ?

**Comment by Jundiyy** [comment]
[[RANK] Final Crossroad ZH v2.zip](https://github.com/xezon/GeneralsRankedMaps/files/6266373/RANK.Final.Crossroad.ZH.v2.zip)
Name update and Oils fixed.

**Comment by TKLyo** [comment]
[[RANK] Final Crossroad ZH v3.zip](https://github.com/xezon/GeneralsRankedMaps/files/6338453/RANK.Final.Crossroad.ZH.v3.zip)
I've retextured the whole map. Added waves. Re-arrange some structures and building placements and changed the audio in the map

**Comment by Jundiyy** [comment]
Uploaded in the wrong issue but no worries, should have been in the first link I sent you.
I'm not sure if you should have touched the structures since mapper only needed textures, but I trust you didn't change stuff around too much. Can't check just yet.
