### ISSUE TITLE
[Candidate 1v1 Glacial Horses V2] Map name needs changing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#38]
**Issue Description**
Map name is unacceptable. Glacial Horses describes a herd of animals and not a location. Map needs a better name.

**Expected behavior**
Map name fits the overall style of Official Maps and ReLaX Maps.

**Comment by KaSSaDo** [comment]
Referring to the lonely well in the middle of the map:
Glacial Well ZH v1
Glacial Fountain ZH v1
Icy Well ZH v1
Icy Fountain ZH v1
Frosty Well ZH v1
Frosty Fountain ZH v1 <--- my favourite because everyone likes alliterations

Referring to the shape of the river:
Horseshoe River ZH v1
Horseshoe Stream ZH v1

**Comment by xezon** [comment]
Frosty Fountain +++++

**Comment by Millard9** [comment]
how about cold horse?/frozen horse?

**Comment by kABUSE1** [comment]
If you still want to change the name I suggest Glacial Shores :P
It sounds similar but less horsey.

**Comment by xezon** [comment]
Sounds good.

**Comment by Millard9** [comment]
Yeah thats a good name i will rename it later today or tomorrow.



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 24/04/2021 15:03 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Comment ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Glacial Horses V2] Map name needs changing (#38)


Sounds good.

**Comment by xezon** [comment]
Be aware kABUSE1 already edited your map.

**Comment by Millard9** [comment]
Oh ok I didn't realise I've been busy



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 24/04/2021 15:46 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Comment ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Glacial Horses V2] Map name needs changing (#38)


Be aware kABUSE1 already edited your map.

**Comment by xezon** [comment]
Map will be renamed to `[RANK] Glacial Shores ZH v1`

**Comment by Millard9** [comment]
OK do you need me to do it?



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 26/04/2021 19:56 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Comment ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Glacial Horses V2] Map name needs changing (#38)


Map will be renamed to [RANK] Glacial Shores ZH v1

**Comment by xezon** [comment]
No it's not necessary. I will do it on Saturday.

**Comment by Millard9** [comment]
OK thanks



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 26/04/2021 20:01 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Comment ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Glacial Horses V2] Map name needs changing (#38)


No it's not necessary. I will do it on Saturday.
