### ISSUE TITLE
[Release 1v1 [RANK] Canyon of the Dead v1] Player is unable to see terrain at all map borders (bottom)

### ISSUE THREAD

**Issue by RisingZH** [xezon/GeneralsRankedMaps#4]
Player is unable to see terrain at all map borders (bottom)

**Comment by ReLaX82** [comment]
Please explain.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/3763eb1c1c1fa7771faa4e4f90c9833947a8b621
