### ISSUE TITLE
[Candidate 1v1 24me ZH v1] Two Oil Derricks are buried under sand

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#42]
**Issue Description**
Two Oil Derricks are buried under sand.

**Expected behavior**
Oil Derricks always show up entirely to match users expectation of visual representation.

**Screenshots**
![shot_20210321_115556_2](https://user-images.githubusercontent.com/4720891/111902295-25fe6800-8a3d-11eb-8d5c-b13248b60819.jpg)

**Comment by Jundiyy** [comment]
I don't think this should be a problem, it makes it more interesting to show the Oils are buried.

**Comment by xezon** [comment]
I think it is acceptable if oils are consistent. Either buried or not buried. Here one is buried and one is not. It looks bad.

**Comment by Jundiyy** [comment]
Ah that's what you meant. I suppose one could look at it that way yes, if certain buildings are in one place then they follow one style. All buried or not.
Also could look at it a different way, for example lots of civ buildings in one area, some are broken and some are not.

**Comment by xezon** [comment]
Fixed (Oil Oasis ZH v1)
