### ISSUE TITLE
[Candidate 1v1 [RANK] Barren Badlands Balanced ZH v2] Is this update necessary?

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#44]
**Issue Description**
It is not clear why this update is necessary.

**Expected behavior**
Please explain why we need this map.

**Comment by ReLaX82** [comment]
The first change actually has been done to fix the bunker.

While fixing the bunker I saw that the layout and civil buildings at the oil are not equal.
Top location you cannot eneter the building, but bottom you can.
This with removing stones inside the middle like in the winter version makes the map more balanced.
Stone are just horrible inside a battlefiled.

**Comment by xezon** [comment]
Update is necessary.
