### ISSUE TITLE
[Candidate 1v1 [RANK] Canyon of the Dead ZH v2] Oil at bottom is difficult to see and has way less camping space behind it

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#45]
**Issue Description**
Oil at bottom is difficult to see and has way less camping space behind it.

**Expected behavior**
Oil areas are similarly designed.

**Screenshots**
![shot_20210321_121718_1](https://user-images.githubusercontent.com/4720891/111902855-b473e900-8a3f-11eb-83da-b85dbc3327af.jpg)

![shot_20210321_121749_2](https://user-images.githubusercontent.com/4720891/111902860-b76ed980-8a3f-11eb-9317-23d661054ed3.jpg)

**Comment by Jundiyy** [comment]
I don't think a v2 is needed, if there are changes that need doing then I suppose this could be looked at, or just use Canyon Frost instead.
Agree about the space but the camera angle issue players can fix themselves at the start of every game.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/3763eb1c1c1fa7771faa4e4f90c9833947a8b621
