### ISSUE TITLE
[Candidate 1v1 [RANK] Early Spring ZH v2] Map lighting has a slight pink tint

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#46]
**Issue Description**
Map lighting has a slight pink tint.

**Expected behavior**
Map lighting looks natural.

**Screenshots**
Comparison between Early Spring and Canyon of the Dead:

![shot_20210321_122646_3](https://user-images.githubusercontent.com/4720891/111903181-42040880-8a41-11eb-87b9-4ed77e9a0bec.jpg)

![shot_20210321_122841_5](https://user-images.githubusercontent.com/4720891/111903188-46302600-8a41-11eb-8026-5c7634a04278.jpg)

**Comment by xezon** [comment]
New map version was supposed to change it. But light has not changed.

![shot_20210328_141536_13](https://user-images.githubusercontent.com/4720891/112751799-21532a00-8fd0-11eb-9b1e-7111e3449900.jpg)

**Comment by ReLaX82** [comment]
The last version I uploaded has TD light.
Can't see an issue here, otherwise I can lower the sun a bit which then is exactly the same as TD.

**Comment by xezon** [comment]
TD light is for desert I assume. This is not desert. Maybe that's why light does not look correct. Ideally light settings are made for the type of terrain that is used.

**Comment by ReLaX82** [comment]
There is now much difference between TD and Canyon Settings. For the sake of it I reduced red light quite a bit. Looka @ GR please and check.

**Comment by xezon** [comment]
Lighting looks good.
![shot_20210417_093827_1](https://user-images.githubusercontent.com/4720891/115105821-91b2f280-9f61-11eb-9c8e-c4d0bb8b2ded.jpg)
