### ISSUE TITLE
[Candidate 1v1 [RANK] Early Spring ZH v2] Bottom base has large ugly fences

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#47]
**Issue Description**
Bottom base has large ugly fences next to supply. Looks unnatural.

**Expected behavior**
Bottom base is fenced of with beautiful rocks or other matching obstacles.

**Screenshots**
![shot_20210321_123313_6](https://user-images.githubusercontent.com/4720891/111903283-cfdff380-8a41-11eb-9771-8d7976f4f01c.jpg)

![shot_20210321_123322_8](https://user-images.githubusercontent.com/4720891/111903287-d40c1100-8a41-11eb-819f-e72c79b55f60.jpg)

**Comment by ReLaX82** [comment]
Rocks both supplies.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/95ccf09930cfb026e184f8f9e7b93974918676f6
