### ISSUE TITLE
[Candidate 1v1 [RANK] Highway 99 ZH v2] AI does not build

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#48]
**Issue Description**
AI does not build on this map.

**Expected behavior**
AI can build and play on this map.

**Comment by ReLaX82** [comment]
AI is still not working. Will ask for help.

**Comment by Jundiyy** [comment]
Can you upload your map with your AI settings here? I can take a look.

**Comment by xezon** [comment]
Map is here:
https://github.com/xezon/GeneralsRankedMaps/tree/main/candidate/maps_1v1_zh/%5BRANK%5D%20Highway%2099%20ZH%20v2

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/9d3a7c54ccc208a5a4e5eb13b0db85f9b0e3526b
