### ISSUE TITLE
[Candidate 1v1 [RANK] Highway 99 ZH v2] Light has strong pink tint

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#49]
**Issue Description**
Light has strong pink tint.

**Expected behavior**
Light has natural colors.

**Screenshots**
![shot_20210321_123543_9](https://user-images.githubusercontent.com/4720891/111903433-965bb800-8a42-11eb-9972-1b897497bfdf.jpg)

**Comment by ReLaX82** [comment]
Changed it to quite equal settings to TD.

**Comment by xezon** [comment]
Lighting still looks strange. See images.

![shot_20210329_113537_4](https://user-images.githubusercontent.com/4720891/112817785-1d341480-9083-11eb-8550-2877e4a82024.jpg)

![shot_20210329_113539_5](https://user-images.githubusercontent.com/4720891/112817800-202f0500-9083-11eb-968d-126bbbf9883d.jpg)

![shot_20210329_113543_6](https://user-images.githubusercontent.com/4720891/112817807-22915f00-9083-11eb-84c7-cb09886b4d53.jpg)

![shot_20210329_113549_7](https://user-images.githubusercontent.com/4720891/112817815-24f3b900-9083-11eb-91f4-b72bceda32d1.jpg)

**Comment by ReLaX82** [comment]
Fixed it!

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/1565464d647b3765bd82de220a46344693eebc11
