### ISSUE TITLE
[Candidate 1v1 [RANK] Highway 99 ZH v2] Oil Derrick at top left has uncommon rotation

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#50]
**Issue Description**
Oil Derrick at top left has uncommon rotation.

**Expected behavior**
Usually oil derricks are always rotated the same for a consistent look. But this map has oil derrick with custom rotation. It does not look proper.

**Screenshots**
![shot_20210321_123754_12](https://user-images.githubusercontent.com/4720891/111903506-e5a1e880-8a42-11eb-86e3-934fbc57ca6a.jpg)

![shot_20210321_123807_13](https://user-images.githubusercontent.com/4720891/111903507-e89cd900-8a42-11eb-9906-cd9143063647.jpg)

**Comment by Jundiyy** [comment]
Whilst they don't have the same rotation, this is becoming more common in maps, many maps have rotated tech buildings now. Feels normal to me.

**Comment by xezon** [comment]
If custom rotation is not necessary, I would recommend to leave them at default rotation for consistent look. OFFICIAL MAPS have them at default rotation always if I recall correctly.

**Comment by ReLaX82** [comment]
Both set to -135.0 to look equal. This is used on some maps.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/9d3a7c54ccc208a5a4e5eb13b0db85f9b0e3526b
