### ISSUE TITLE
[Candidate 1v1 [RANK] Melting Snow ZH v4] Light has strong green tint

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#52]
**Issue Description**
Light has strong green tint.

**Expected behavior**
Light color looks natural.

**Screenshots**
![shot_20210321_124604_15](https://user-images.githubusercontent.com/4720891/111903640-9a3c0a00-8a43-11eb-9e6f-cc6cfe39f140.jpg)

**Comment by Jundiyy** [comment]
Whilst I agree it's not the normal type of lighting, I think all the played have become used to it and don't find it different. Perhaps this type of lighting could be passed for future maps based on it being 'natural' for players? 
Although regarding this map, I don't know why we need a v4, any major changes?

**Comment by xezon** [comment]
Different lighting is ok, but it needs to look natural, otherwise it just look amateur and should not be part of Ranked Maps, which has many maps with excellent lighting so we don't need maps with broken light.

**Comment by ReLaX82** [comment]
TD-alike light used now. I fear that when we are done here, everything looks the same.
Map see post #259.

**Comment by xezon** [comment]
Light looks better now. A bit too pink but acceptable. Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/94081796f32c6fb19993b9e6355c07628a715680

![shot_20210327_172550_3](https://user-images.githubusercontent.com/4720891/112727288-2ce81780-8f22-11eb-840b-24269856925c.jpg)
