### ISSUE TITLE
[Candidate 1v1 Arab Tragedy ZHv2] Water has unnatural color

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#54]
**Issue Description**
Water has unnatural color.

**Expected behavior**
Water looks natural.

**Screenshots**
![shot_20210321_125003_17](https://user-images.githubusercontent.com/4720891/111903990-da4fbc80-8a44-11eb-82d9-81fbcc5f272a.jpg)

**Comment by SpeCoV1k** [comment]
very natural color of water ;)
https://sfw.so/uploads/posts/2012-07/1343501979_more.jpg
https://images.wallpaperscraft.ru/image/okaen_bereg_voda_obryv_115460_3840x2160.jpg
https://i.pinimg.com/originals/ca/29/17/ca2917d3e592586267317d59cab74fa2.jpg

**Comment by xezon** [comment]
I think it is too bright. A bit darker would look more realistic.

**Comment by SpeCoV1k** [comment]
For this topic and this https://github.com/xezon/GeneralsRankedMaps/issues/53
[https://www.gamereplays.org/community/uploads/post-103811-1616938265.png](url)

**Comment by Jundiyy** [comment]
I have given Spec some in depth feedback to fix some balance problems.

**Comment by xezon** [comment]
Water looks good in new version.
![shot_20210417_101525_10](https://user-images.githubusercontent.com/4720891/115106574-e3f61280-9f65-11eb-9355-bec8342df25e.jpg)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/fec5c24c70a72c32dc61aedda0db98749da52b59
