### ISSUE TITLE
[Candidate 1v1 Battle Plan ZH v1] Intro title is not consistent with other ranked maps

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#55]
**Issue Description**
Intro title says "Created by ReLaX!"

**Expected behavior**
Intro title says "Map created by ReLaX", or "Battle Plan, by ReLaX".

**Screenshots**
![shot_20210321_130734_26](https://user-images.githubusercontent.com/4720891/111904323-a37aa600-8a46-11eb-8ba3-46c504783e1f.jpg)

**Comment by ReLaX82** [comment]
Fixed, as I have some issue with ZIP it can be found in the Ranks topic on GR post #258.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/231933eb8becbbd856c169e19350b09087108e40
