### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Title text is not concise

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#59]
**Issue Description**
Title says: "Freezing Rain v1 by Millard9, queenmuff & Spalding."

**Expected behavior**
Title says: "Freezing Rain, by Millard9, queenmuff & Spalding"

**Screenshots**
![shot_20210321_132357_31](https://user-images.githubusercontent.com/4720891/111904928-7b407680-8a49-11eb-9419-0579bcc324ef.jpg)

**Comment by Millard9** [comment]
Can change this Easy will do so if required.

**Comment by xezon** [comment]
It is not required to change anything on the map. Map will not be eligible for Ranked Maps and GenTool Auto download with this however.

**Comment by Millard9** [comment]
So if I change the Text to "Freezing Rain v2 by Millard9, queenmuff & Spalding" it will be

**Comment by xezon** [comment]
No. "Freezing Rain v2 by Millard9, queenmuff & Spalding" will not qualify. "Freezing Rain, by Millard9, queenmuff & Spalding" will.
If you look at other Ranked Maps we have 2 styles of credits:
a) Map created by X
b) MapName, by X

I will accept these 2 formats. This is required for consistent style between all maps.

**Comment by xezon** [comment]
Issue is not fixed in new version

![shot_20210327_104653_1](https://user-images.githubusercontent.com/4720891/112717251-b4666400-8eeb-11eb-8430-8eb848418de8.jpg)

**Comment by Millard9** [comment]
I'm not sure what you mean by it not being concise. I thought Freezing Rain v2 by Millard9, queenmuff & Spalding. Was correct?



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 27/03/2021 10:01 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Assign ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Freezing Rain v2] Title text is not concise (#59)


Issue is not fixed in new version

[shot_20210327_104653_1]<https://user-images.githubusercontent.com/4720891/112717251-b4666400-8eeb-11eb-8430-8eb848418de8.jpg>

**Comment by xezon** [comment]
Repository front page explains rules for credit text:
https://github.com/xezon/GeneralsRankedMaps

**Comment by Millard9** [comment]
So just to confirm you want it to say "Made by Millard9, queenmuff & Spalding. Freezing Rain ZH v2" is this correct?



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 27/03/2021 10:22 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Assign ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Freezing Rain v2] Title text is not concise (#59)


Repository front page explains rules for credit text:
https://github.com/xezon/GeneralsRankedMaps

**Comment by xezon** [comment]
I already posted above twice how it should be named. I copy it again:

"Freezing Rain, by Millard9, queenmuff & Spalding"

**Comment by Millard9** [comment]
Ok i will change it to that then. thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/615b40c2937fdedfec1d5ae9f72917f978a3c911
