### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Some structures are buried in snow too much

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#60]
**Issue Description**
Some structures are buried in snow too much.

**Expected behavior**
Important structures are not sunken by terrain all that much for consistency sake.

**Screenshots**
![shot_20210321_132534_32](https://user-images.githubusercontent.com/4720891/111904969-ae830580-8a49-11eb-81d3-57eaae8d32f4.jpg)

![shot_20210321_132548_33](https://user-images.githubusercontent.com/4720891/111904972-b0e55f80-8a49-11eb-828a-5532903807a3.jpg)

**Comment by Jundiyy** [comment]
I like the supplies in such a way, brings something new to ZH, the Oils maybe don't look as good.

**Comment by Millard9** [comment]
The buildings covered in snow are by Design it looks good

**Comment by xezon** [comment]
Issue is not marked as blocker so does not need to be fixed for Ranked Map. However map will not qualify for GenTool Auto Download with this.

**Comment by Millard9** [comment]
> Issue is not marked as blocker so does not need to be fixed for Ranked Map. However map will not qualify for GenTool Auto Download with this.

May I ask why it won't qualify if it's the map makers choice to add a bit of snow on some supplies an oils?

**Comment by xezon** [comment]
Because oils and supplies are important structures that ideally are fully visible to players. It looks like a design issue when they are partly clipped into terrain. I would object to this requirement if the implementation of snow coverage was beautifully done, but it is not and therefore I will not accept this as a quality map that should be installed to every GenTool user.

**Comment by Millard9** [comment]
So i have yo change the design of a map that took weeks to make just because you don't like a cosmetic feature that doesn't hinder gameplay in anyway? How is that fair on the Map designer? I'm not trying to be rude or disrespectful but its seems a little bit dictatorish in my opinion.

**Comment by xezon** [comment]
All current Ranked Maps have fully exposed money structures. And so do Official Maps. That is the way it should be. The quality process of maps is in place to ensure that only high quality maps are presented to the user. I understand that every map creator has different preferences, however, I need to oversee the Ranked Maps as a whole and such design simply does not fit in quality standards of Ranked Maps.

You do not need to change design if you don't want to.

**Comment by Millard9** [comment]
I appreciate that you have to set a level of standards however although the olis and supplies are covered a bit they are clearly visible and it doesn't hinder gameplay.  I can try and make it look a bit better if that will sway the decision?  

Plus everyone knows there's no point in having a ranked map if its not on gentool. Because ideally everyone will have it

**Comment by xezon** [comment]
Most supplies and oils look good in new version. There are 2 more oil derricks with bad terrain clipping:

![shot_20210327_104742_2](https://user-images.githubusercontent.com/4720891/112717233-8ed95a80-8eeb-11eb-8c9c-2b2563a3b625.jpg)

![shot_20210327_104747_3](https://user-images.githubusercontent.com/4720891/112717236-926ce180-8eeb-11eb-9fa9-9e477863f9cc.jpg)

![shot_20210327_104800_4](https://user-images.githubusercontent.com/4720891/112717238-94cf3b80-8eeb-11eb-9f0f-2c31544ac8ea.jpg)

**Comment by Millard9** [comment]
I'll fix this.



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 27/03/2021 10:00 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Assign ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Freezing Rain v2] Some structures are buried in snow too much (#60)


Most supplies and oils look good in new version. There are 2 more oil derricks with bad terrain clipping:

[shot_20210327_104742_2]<https://user-images.githubusercontent.com/4720891/112717233-8ed95a80-8eeb-11eb-8c9c-2b2563a3b625.jpg>

[shot_20210327_104747_3]<https://user-images.githubusercontent.com/4720891/112717236-926ce180-8eeb-11eb-9fa9-9e477863f9cc.jpg>

[shot_20210327_104800_4]<https://user-images.githubusercontent.com/4720891/112717238-94cf3b80-8eeb-11eb-9f0f-2c31544ac8ea.jpg>

**Comment by xezon** [comment]
Bottom oil looks good. Oil at top is floating above terrain.

![shot_20210327_195629_3](https://user-images.githubusercontent.com/4720891/112731492-d84f9700-8f37-11eb-9170-6a8dd02e32c3.jpg)

**Comment by xezon** [comment]
Looks ok now.

![shot_20210328_132254_5](https://user-images.githubusercontent.com/4720891/112750413-c538d780-8fc8-11eb-8c3c-2dab4f4ad6b1.jpg)
