### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Snow terrain has pink tint

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#61]
**Issue Description**
Snow terrain has pink tint.

**Expected behavior**
Snow looks natural. White.

**Screenshots**

Pink:
![shot_20210321_132357_31](https://user-images.githubusercontent.com/4720891/111905069-29e4b700-8a4a-11eb-98e0-5f563c8ec05b.jpg)

White:
![shot_20210321_133205_34](https://user-images.githubusercontent.com/4720891/111905077-3406b580-8a4a-11eb-8f76-c9d12df131e9.jpg)

**Comment by Millard9** [comment]
Its set to a different time of day to help with strain on the eyes Size said it was too bright.

Can be changed however prefer not to

**Comment by xezon** [comment]
Issue is not marked as blocker so does not need to be fixed for Ranked Map. However map will not qualify for GenTool Auto Download with this.

**Comment by xezon** [comment]
Checked latest version. Terrain still has pink tint.

Freezing Rain:
![shot_20210327_104939_6](https://user-images.githubusercontent.com/4720891/112717178-402bc080-8eeb-11eb-9148-7ee720166726.jpg)

Other snow map:
![shot_20210327_105004_7](https://user-images.githubusercontent.com/4720891/112717196-56d21780-8eeb-11eb-9d2e-cd0a5c12ca98.jpg)

**Comment by Millard9** [comment]
I reset all the lighting options to default.  Thought that would of slowed it. I will look at other map settings and try to fix this.



Sent from my Galaxy



-------- Original message --------
From: xezon ***@***.***>
Date: 27/03/2021 09:58 (GMT+00:00)
To: xezon/GeneralsRankedMaps ***@***.***>
Cc: Millard9 ***@***.***>, Assign ***@***.***>
Subject: Re: [xezon/GeneralsRankedMaps] [Candidate 1v1 Freezing Rain v2] Snow terrain has pink tint (#61)


Checked latest version. Terrain still has pink tint.

Freezing Rain:
[shot_20210327_104939_6]<https://user-images.githubusercontent.com/4720891/112717178-402bc080-8eeb-11eb-9148-7ee720166726.jpg>

Other snow map:
[shot_20210327_105004_7]<https://user-images.githubusercontent.com/4720891/112717196-56d21780-8eeb-11eb-9d2e-cd0a5c12ca98.jpg>

**Comment by xezon** [comment]
New lighting is much better. Shadow light is a bit too blue. Maybe can be tweaked a bit.

![shot_20210327_195702_4](https://user-images.githubusercontent.com/4720891/112731465-ac341600-8f37-11eb-9c4b-47ddde550494.jpg)

**Comment by xezon** [comment]
Shadow color still is a bit too blue I think.

![shot_20210328_131703_4](https://user-images.githubusercontent.com/4720891/112750371-84d95980-8fc8-11eb-8116-c4fc5647c817.jpg)

**Comment by Millard9** [comment]
I copied Immanent victory shadow settings, before when you mentioned it was set a default, if you know of a map that doesn't have this can you tell me and i will copy setting.

**Comment by xezon** [comment]
You can look into some of the other snow maps.

**Comment by Millard9** [comment]
ok so i have changed the shadows to the same as [RANK] Snowy Drought v4,
![Untitled](https://user-images.githubusercontent.com/81384841/112753708-a9d1ca80-8fd0-11eb-982e-4067b3b3278d.png) 
Freezing Rain v2
![1Untitled](https://user-images.githubusercontent.com/81384841/112753719-b8b87d00-8fd0-11eb-822d-3a28927c4009.png)
[RANK] Snowy Drought v4

**Comment by xezon** [comment]
Keep in mind shadow color is relative to your light color. Copying it from another map may not work well, because map terrain and light can differ vastly. Ideally you balance light and shadow colors for each map individually.

**Comment by Millard9** [comment]
I have now changed all the lighting to be the same as snowy v4

**Comment by xezon** [comment]
Would it be possible to make it slightly less pinky? Other than that lighting look very consistent now.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7586345394c90cb6dea8b8570de4974f51c16c8e

![shot_20210330_230447_1](https://user-images.githubusercontent.com/4720891/113056855-a135eb80-91ac-11eb-874c-b2029f80c11d.jpg)
