### ISSUE TITLE
[Candidate 1v1 Glacial Horses V1] Map looks empty and boring design wise

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#65]
**Issue Description**
Map looks empty and boring design wise.

**Expected behavior**
Map has nice design and looks beautiful.

**Screenshots**
![shot_20210321_134116_39](https://user-images.githubusercontent.com/4720891/111905306-3cabbb80-8a4b-11eb-83c4-61389ed22588.jpg)

![shot_20210321_134124_40](https://user-images.githubusercontent.com/4720891/111905309-3fa6ac00-8a4b-11eb-9e13-75cb0c14a443.jpg)

![shot_20210321_134156_41](https://user-images.githubusercontent.com/4720891/111905312-41706f80-8a4b-11eb-8eae-0aaf10518e8c.jpg)

**Comment by ReLaX82** [comment]
Yes, too less textures, also the path is looking wired, colour wise and the heights as well.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/d0658d193a96c0877f08444b867c728e4766d5e7
