### ISSUE TITLE
[Candidate 1v1 Imminent Victory] Terrain in home base looks flat but cannot be built on.

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#67]
**Issue Description**
Terrain in home base looks flat but cannot be built on.

**Expected behavior**
All terrain that looks flat can be built on, especially if it is around supplies.

**Screenshots**
![shot_20210321_134511_42](https://user-images.githubusercontent.com/4720891/111905441-ef7c1980-8a4b-11eb-91c4-35299cb6b27d.jpg)

![shot_20210321_134605_43](https://user-images.githubusercontent.com/4720891/111905442-f1de7380-8a4b-11eb-8f8d-f14fbe5c6ffe.jpg)

**Comment by Jundiyy** [comment]
It doesn't look flat? You can see the left side is raised compared to the right. And that line is the only part you can't build on as it is where the land starts to raise (has a different texture colour for this reason). Please look at your pics, you can see the land is raised.
All the land around the supply is perfectly flat to place a perfect China/GLA supply. Then it starts to dip as it moves to ways the CC so you can't build on it.

**Comment by Jundiyy** [comment]
I've worked on this for quite some time today, once I'm happy with the outcome I will try and upload within a few days.

**Comment by Jundiyy** [comment]
[[RANK] Imminent Victory ZH v2.zip](https://github.com/xezon/GeneralsRankedMaps/files/6215541/RANK.Imminent.Victory.ZH.v2.zip)
I have made the land flatter so you can build all around now.
I have also removed the Jarmen sound

**Comment by xezon** [comment]
Fixed in [RANK] Imminent Victory ZH v2
