### ISSUE TITLE
[Release 1v1 [RANK] Jungle Wolf ZH v2] Player is unable to see terrain at all map borders (top and bottom)

### ISSUE THREAD

**Issue by RisingZH** [xezon/GeneralsRankedMaps#7]
Field of view - top and bottom

**Comment by SpeCoV1k** [comment]
Now:
https://www.gamereplays.org/community/uploads/post-103811-1616940192.png
https://www.gamereplays.org/community/uploads/post-103811-1616940199.png
v3: https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=861482

**Comment by xezon** [comment]
@RisingZH please test map and check if your problem is fixed.

**Comment by RisingZH** [comment]
Thanks for looking at this but still not fixed.

https://imgur.com/a/RpDE63i (There is a chinook collecting from the pile)

@SpeCoV1k

**Comment by SpeCoV1k** [comment]
> Thanks for looking at this but still not fixed.
> 
> https://imgur.com/a/RpDE63i (There is a chinook collecting from the pile)
> 
> @SpeCoV1k

i can just change position of this supply dock, but aften any unit will can drive around up dock (make same with sup dock down player) - ok?

**Comment by xezon** [comment]
@RisingZH

**Comment by RisingZH** [comment]
Hmm perhaps leave this one then. Moving the dock so players can drive round could have a big impact.

**Comment by xezon** [comment]
Fixed
![shot_20210417_095412_5](https://user-images.githubusercontent.com/4720891/115106098-1e11e500-9f63-11eb-86f2-7a416a1d410b.jpg)
