### ISSUE TITLE
[Candidate 1v1 Tournament Himalaya V3] Map has no ambient sounds

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#75]
**Issue Description**
Map has no ambient sounds.

**Expected behavior**
Map has ambient sounds.

**Comment by A5SA5SIN** [comment]
does ambient sound means sound of surrounding like noisy village something like that?

**Comment by xezon** [comment]
Yes.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/bcdd9152977b22818c174e3cc2e68880e73c0216
