### ISSUE TITLE
[Candidate 1v1 Tournament Himalaya V2] Title text is not concise

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#76]
**Issue Description**
Title text says: "MISSING: 'Tourn.Himalaya Made By A5SA5SIN Play Fair And HaveFun'"

**Expected behavior**
Title text says "Tournament Himalaya, by A5SA5SIN"

**Screenshots**
![shot_20210322_141854_9](https://user-images.githubusercontent.com/4720891/111996368-3df7e980-8b1a-11eb-9c2e-25a3b3248c06.jpg)

**Comment by A5SA5SIN** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/81484691/112814952-63ed3300-90b2-11eb-8a41-15b7f3885c7a.png)
before i release version 3 do you think this text is ok?

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/9c3d6405a7e5aee03da0eba37f37615db63c09e7
