### ISSUE TITLE
[Candidate 1v1 Tournament Himalaya V2] Terrain displays several unrealistic grass ramps

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#77]
**Issue Description**
Terrain displays several unrealistic grass ramps.

**Expected behavior**
Grass ramps have different texture to look more like man-made elevation modifications.

**Screenshots**
![shot_20210322_142445_11](https://user-images.githubusercontent.com/4720891/111996687-9333fb00-8b1a-11eb-8703-314ad204af2a.jpg)

**Comment by A5SA5SIN** [comment]
Hey Xezon i made a ew changes do you think this ok
![Screenshot (27)](https://user-images.githubusercontent.com/81484691/112729803-0d281200-8f69-11eb-98f1-b80895aabc53.png)
![Screenshot (30)](https://user-images.githubusercontent.com/81484691/112729804-144f2000-8f69-11eb-8a5b-94280254b636.png)
![Screenshot (31)](https://user-images.githubusercontent.com/81484691/112729811-1a450100-8f69-11eb-8c17-f1158839ffe3.png)

**Comment by A5SA5SIN** [comment]
![Uploading Screenshot (33).png…]()

**Comment by A5SA5SIN** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/81484691/112729890-7445c680-8f69-11eb-9d87-e48032c11b11.png)

**Comment by xezon** [comment]
Did you tweak the look of the ramps?

**Comment by A5SA5SIN** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/81484691/112746661-e27a9f80-8fe2-11eb-839a-4574a7993f0e.png)
it's better i guess

**Comment by xezon** [comment]
Grass ramp is ok but ideally it looks natural. I have seen other maps with grass ramps. I think you just need to smooth out the elevation changes. I would need your updated map files to review your changes.

**Comment by A5SA5SIN** [comment]
[Tournament Himalaya V3.zip](https://github.com/xezon/GeneralsRankedMaps/files/6220725/Tournament.Himalaya.V3.zip)
Here my version 3 and please tell me anything if there something need to fix

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/9c3d6405a7e5aee03da0eba37f37615db63c09e7

Grass ramps look natural now.

There still is issue #75 
And I added new issue #125

![shot_20210330_102519_11](https://user-images.githubusercontent.com/4720891/112957956-41a2f600-9142-11eb-91e1-911f27b57d90.jpg)
