### ISSUE TITLE
[Candidate 1v1 White Hell ZH v1] There are no ambient sounds in home base

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#79]
**Issue Description**
There are no ambient sounds in home base.

**Expected behavior**
Map has ambient sounds everywhere.

**Comment by ReLaX82** [comment]
I don't know who raised this issue, but I can tell that there are no sounds at all, which I simply added now!
See here: https://www.gamereplays.org/community/index.php?showtopic=1048527&st=240&gopid=10403747&#

**Comment by xezon** [comment]
I checked. Cricket sounds were added. There should be no crickets on snow terrain.

**Comment by ReLaX82** [comment]
Owls:
Die meisten Eulen sind nachtaktiv. Ausnahmen sind beispielsweise die tagaktive Schnee-Eule, die Sperbereule, die Sumpfohreule oder der oft auch am Tag aktive Sperlingskauz.
--> This means owls can surely be active over day, not only night ;-)

You will only find birds, wolves, city, wind, crois now if that is convenient enough for you, please test.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/f67b8fd0b6f4281d77f41388962a1577dff4e2ff
