### ISSUE TITLE
[Candidate 1v1 Imminent Victory] Jarmen voice plays at start of map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#80]
**Issue Description**
Jarmen voice plays at start of map.

**Expected behavior**
No Jarmen voice at start of map.

**Comment by Jundiyy** [comment]
This will be removed for any of my maps that become ranked, my non-ranked maps have them and since this is currently my non-ranked map, that's the reason it has it. If there are no other issues with my maps then I will rename them to RANK and remove the sounds.

**Comment by xezon** [comment]
Fixed in [RANK] Imminent Victory ZH v2
