### ISSUE TITLE
[Candidate 1v1 Freezing Rain v2] Ambient sound is missing

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#82]
**Issue Description**
Ambient sound is missing.

**Expected behavior**
Map has ambient sound.

**Comment by xezon** [comment]
Sounds are good for the most part. A problem appears to be sound over Oil Refinery. There is water and bird sounds. I think this sound would fit better in middle section where the water fountain and the trees are.

![shot_20210327_195426_1](https://user-images.githubusercontent.com/4720891/112731422-6ecf8880-8f37-11eb-8124-80ccf7ada4fc.jpg)

![shot_20210327_195443_2](https://user-images.githubusercontent.com/4720891/112731425-71ca7900-8f37-11eb-92de-3250948c9469.jpg)

**Comment by Millard9** [comment]
I have changed the sound around, please take a look in the version i just posted on GameReplays

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/7988b3afb863d8b4635ffe121e4a912d568cba7b
