### ISSUE TITLE
[Candidate 1v1 Farmlands of the Fallen ZH v3] Ambient sound is missing on most parts of the map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#83]
**Issue Description**
Ambient sound is missing on most parts of the map.

**Expected behavior**
Ambient sound is audible everywhere.

**Comment by ReLaX82** [comment]
V3 looks way more "unattractive" than v3 btw.
Wasn't there a rule to use ZH v3 instead?
Anyone knows how I can contact Bamovich?
If I cannot, I could do the changes.

**Comment by xezon** [comment]
Yes map can be renamed to **[RANK] Farmlands of the Fallen ZH v3**

**Comment by ReLaX82** [comment]
https://www.gamereplays.org/community/index.php?showtopic=1051084

Waiting for reply here, otherwise I will upload this version and check last time once again.

**Comment by xezon** [comment]
Some more sounds have been placed, but most parts of map still have no sound.

![shot_20210405_190034_6](https://user-images.githubusercontent.com/4720891/113601397-90202b00-9641-11eb-9136-21c50b2851fb.jpg)
![shot_20210405_190044_7](https://user-images.githubusercontent.com/4720891/113601398-90b8c180-9641-11eb-8bde-adc017315d07.jpg)
![shot_20210405_190051_8](https://user-images.githubusercontent.com/4720891/113601400-91515800-9641-11eb-816b-66db665d4f31.jpg)
![shot_20210405_190059_9](https://user-images.githubusercontent.com/4720891/113601404-91e9ee80-9641-11eb-9b7c-2e0e4d5a4cdd.jpg)

**Comment by xezon** [comment]
I checked audio of new Farmlands version that was supplied somewhere. Birds sound is not well setup. When you scroll slowly from base to farms, there is a very distinct hard cut between no bird and bird sound. This sounds very unpleasant. Bird sound itself also does not fit well, as it is quit intense for farm. It would be better suited to put Ravens on farm, and birds in trees.

**Comment by Jundiyy** [comment]
Wasn't planning to do this one but in case Relax doesn't get time. I couldn't find any ambient sounds in the map I downloaded today from github so I added some in. Not too many and lowered the wind sounds the way Mixery did.
[Farmlands of the Fallen ZH v3.zip](https://github.com/xezon/GeneralsRankedMaps/files/6399128/Farmlands.of.the.Fallen.ZH.v3.zip)

**Comment by xezon** [comment]
Ambient audio is acceptable. Maybe replace chickens on the windmills with a less dominant sound?

**Comment by Jundiyy** [comment]
There's chickens there? Lol I didn't even know, (not currently loading the game up) they must come default with the windmill since I didn't place them. I will take a look.

**Comment by Jundiyy** [comment]
I wasn't sure where the raven sounds were, so I used another bird sound from Forgotten Forest.
And lowered the chicken sounds as well. 
[Farmlands of the Fallen ZH v3.zip](https://github.com/xezon/GeneralsRankedMaps/files/6406128/Farmlands.of.the.Fallen.ZH.v3.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/43cd1d204b5f226cad948b07472b5a156d7ca26d
