### ISSUE TITLE
[Candidate 2v2 Bricks 2v2 ZH v1] Terrain under Command Center is not flat

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#85]
**Issue Description**
Terrain under Command Center is not flat.

**Expected behavior**
Terrain under Command Center is flat.

**Screenshots**
![shot_20210323_131616_2](https://user-images.githubusercontent.com/4720891/112145149-50395c80-8bda-11eb-9d36-03be1f26241f.jpg)

**Comment by kABUSE1** [comment]
Fixed.
[Bricks 2v2 ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6370554/Bricks.2v2.ZH.v1.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/46f13a6b2d6ad92413ff1834bcbdd188ac518601
