### ISSUE TITLE
[Candidate 2v2 Bricks 2v2 ZH v1] Map could have better name

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#86]
**Issue Description**
"Bricks" map name makes no sense.

**Expected behavior**
Map name could describe map better.

**Comment by kABUSE1** [comment]
No bricks to be found in the map.

What about "Brickless Prairie"?

**Comment by xezon** [comment]
Will be renamed to "Final Departure" in regards to those trains there waiting to depart.
