### ISSUE TITLE
[Candidate 2v2 Burning Deadline ZH v1] Strange texture is visible on top map border

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#87]
**Issue Description**
Strange texture is visible on top map border.

**Expected behavior**
There is no such texture.

**Screenshots**
![shot_20210323_132317_4](https://user-images.githubusercontent.com/4720891/112146015-5976f900-8bdb-11eb-9288-ab820c305a84.jpg)

**Comment by kABUSE1** [comment]
Fixed.

Also corrected the atrociously placed trigger areas for AI.

[Uploading Burning Deadline ZH v1.zip…]()

**Comment by xezon** [comment]
The map uploaded failed here. Please re upload.

**Comment by kABUSE1** [comment]
[Burning Deadline ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6372081/Burning.Deadline.ZH.v1.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/76d64ce0538d17e68c9a5db3849462dae23c3c4a
