### ISSUE TITLE
[Candidate 2v2 Bursting Asunder] Light source is in north, which make shadows look very dark by default

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#88]
**Issue Description**
Light setup looks strange. Sun likely needs a little angle to make default view look more pleasing.

**Expected behavior**
Light and shadow intensity have a good balance.

**Screenshots**
![shot_20210323_132942_5](https://user-images.githubusercontent.com/4720891/112146680-25e89e80-8bdc-11eb-85cb-a7882505c246.jpg)

**Comment by Jundiyy** [comment]
I don't understand what is wrong here? It's normal ZH lighting with the sun in the north, I thought only unrealistic lighting was a problem?

**Comment by xezon** [comment]
It is very uncommon to have light on exact north. Objects facing the camera are therefore always in shade. It looks odd this way. You can try to play with the angle to improve the look.

**Comment by Jundiyy** [comment]
I tried to do it without causing changes to the texture colour, this is what I got, is is good enough?
1st is the original, second is the new one.
![Original](https://user-images.githubusercontent.com/79164303/112190384-da92b800-8bfc-11eb-8afb-d9ececcfc2c0.PNG)
![New](https://user-images.githubusercontent.com/79164303/112190396-dd8da880-8bfc-11eb-9297-35113e949794.PNG)

**Comment by xezon** [comment]
Yes this looks better because the forward facing object surfaces are no longer in the shade and therefore are not that dark.

**Comment by Jundiyy** [comment]
[[RANK] Bursting Asunder ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6215550/RANK.Bursting.Asunder.ZH.v1.zip)
Shadow moved according to what the pic looks like above.
Jarmen voice removed.

**Comment by xezon** [comment]
Fixed in [RANK] Bursting Asunder ZH v1
