### ISSUE TITLE
[Candidate 2v2 Bursting Asunder] Jarmen voice is audible on map start

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#89]
**Issue Description**
Jarmen voice is audible on map start.

**Expected behavior**
No Jarmen voice.

**Comment by Jundiyy** [comment]
👍 will be removed when renamed, as currently it's still part of my non-ranked maps.

**Comment by xezon** [comment]
Fixed in [RANK] Bursting Asunder ZH v1
