### ISSUE TITLE
[Release 1v1 [RANK] Make Make 2 ZH v3] Player is unable to see terrain at all map borders (top)

### ISSUE THREAD

**Issue by RisingZH** [xezon/GeneralsRankedMaps#9]
Field of view - top

**Comment by SpeCoV1k** [comment]
Here not understand? can you pic screenshot? cos i in game see all -_-

**Comment by xezon** [comment]
@RisingZH please attach images.

**Comment by RisingZH** [comment]
https://imgur.com/a/340khru

Same issue as the others, unable to see chinooks.

**Comment by SpeCoV1k** [comment]
So, all new change here: https://www.gamereplays.org/community/uploads/post-103811-1617454105.png
Map dL: https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=861804

**Comment by xezon** [comment]
@RisingZH

**Comment by RisingZH** [comment]
Looks good.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/fe4a1c5743aa13103a824bf8b9fc637e6cb1b039
