### ISSUE TITLE
[Candidate 2v2 Drowning Horses V1] Map has no ambient sound

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#94]
**Issue Description**
Map is missing ambient sound.

**Expected behavior**
Map has ambient sound.

**Comment by xezon** [comment]
Map has a few ambient sounds with https://github.com/xezon/GeneralsRankedMaps/commit/9e9dbc4f720a4ce32093656a8888ad2815a3677c

Could add some water sounds at the big water locations. Overall map is still quiet. Wind + cow + dogs only.

**Comment by Millard9** [comment]
done, sent to you via discord

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/d1ff053c80b688be2a53a04a92cad346d65ed90e
