### ISSUE TITLE
[Candidate 2v2 FallOut ZH v1] Car tracks are purple

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#95]
**Issue Description**
Car tracks are purple.

**Expected behavior**
Car tracks have suitable color for terrain texture beneath.

**Screenshots**
![shot_20210323_135903_17](https://user-images.githubusercontent.com/4720891/112150405-55010f00-8be0-11eb-83a8-5ad958c05faf.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/706590269a242fc8c05cfdb34a4ae54cc8fcd9bb
