### ISSUE TITLE
[Candidate 2v2 FallOut ZH v1] Strange texture is located at top of map

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#96]
**Issue Description**
Strange texture is located at top of map.

**Expected behavior**
No strange texture on terrain.

**Screenshots**
![shot_20210323_135752_15](https://user-images.githubusercontent.com/4720891/112150502-74983780-8be0-11eb-9ecc-3979c2d035db.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by Jundiyy** [comment]
Fixed in #23 
Sorry @Newgate-M17 I was working on the tweaking and fixed the texture as well.

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/706590269a242fc8c05cfdb34a4ae54cc8fcd9bb
