### ISSUE TITLE
[Candidate 2v2 Lion Heart] Map has several usable fast cars

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#98]
**Issue Description**
Map has several usable fast cars.

**Expected behavior**
Map has no fast cars.

**Screenshots**
![shot_20210323_170618_1](https://user-images.githubusercontent.com/4720891/112179055-9f8f8500-8bfa-11eb-8d8b-8be56da764e2.jpg)

**Comment by Newgate-M17** [comment]
I'll work on this one

**Comment by Jundiyy** [comment]
Sorry Newgate, didn't see this was assigned to you. Just saw it now that I uploaded the file.
[Lion Heart.zip](https://github.com/xezon/GeneralsRankedMaps/files/6399190/Lion.Heart.zip)

**Comment by xezon** [comment]
Fixed with https://github.com/xezon/GeneralsRankedMaps/commit/e5200ea1e841185fbcee36f54872a8f5684e8289
