### ISSUE TITLE
[Candidate 2v2 Rubies and Pearls] Jarmen voice is audible on map start

### ISSUE THREAD

**Issue by xezon** [xezon/GeneralsRankedMaps#99]
**Issue Description**
Jarmen voice is audible on map start.

**Expected behavior**
No Jarmen voice.

**Comment by Jundiyy** [comment]
[[RANK] Rubies and Pearls ZH v1.zip](https://github.com/xezon/GeneralsRankedMaps/files/6215547/RANK.Rubies.and.Pearls.ZH.v1.zip)
Jarmen voice has been removed.
Insect voices replaced.

**Comment by xezon** [comment]
There are still cricket sounds in the map center.

**Comment by xezon** [comment]
Fixed in [RANK] Rubies and Pearls ZH v1
